// ============================================================
// LAUNCHPAD-13 — data.js
// Static content: rocket catalog, cargo manifest items, and the
// launch-outcome library. No DOM/canvas code lives in this file.
//
// Rocket specs are rounded, public-domain figures for real vehicles,
// kept for flavor/education — treat exact numbers as approximate, not
// a technical reference.
// ============================================================

const ROCKETS = [
  {
    id: "falcon-heavy",
    name: "Falcon Heavy",
    designation: "SpaceX",
    country: "USA",
    flag: "🇺🇸",
    env: { time: "day", terrain: "coastal", locale: "Cape Canaveral, USA" },
    className: "Heavy-lift, partially reusable launch vehicle",
    tagline: "Three cores, one very confident landing burn.",
    stages: 2,
    heightM: 70,
    diameterM: 12.2,
    liftoffMassT: 1420,
    payload: "63,800 kg to LEO",
    primary: { name: "Merlin 1D", cycle: "Gas-generator kerolox, 27 across 3 cores", count: 27, thrustEach: "845 kN" },
    secondary: { name: "Cold-gas nitrogen thrusters", count: 4, purpose: "Upper-stage roll control" },
    boosters: { name: "Falcon 9 side cores", count: 2, type: "Reusable liquid strap-on", thrustEach: "7,600 kN (9 engines each)" },
    propellant: "RP-1 / LOX",
    guidance: "Triple-redundant flight computer, inertial + GPS fusion",
    flavor: "Two side boosters bolted to a stretched Falcon 9 core. Known for synchronized landings that look better than most air shows.",
    palette: { hull: "#f2f2f2", hullShadow: "#9aa0a6", accent: "#1c1c1e", trim: "#2b2f36", window: "#8fd3ff", flameCore: "#fff2b0", flameOuter: "#ff7a3d" },
    build: { boosters: 2, boosterHeightFrac: 0.92, nose: "point", fin: "straight", stripes: false, legs: true, gridfins: true },
  },
  {
    id: "starship",
    name: "Starship",
    designation: "SpaceX",
    country: "USA",
    flag: "🇺🇸",
    env: { time: "twilight", terrain: "desert", locale: "Starbase, Texas, USA" },
    className: "Super-heavy, fully-reusable launch system",
    tagline: "The biggest thing that's ever tried to come back.",
    stages: 2,
    heightM: 121,
    diameterM: 9,
    liftoffMassT: 5000,
    payload: "100,000+ kg to LEO (fully reusable target)",
    primary: { name: "Raptor 2/3", cycle: "Full-flow staged-combustion methalox", count: 39, thrustEach: "~2,300 kN" },
    secondary: { name: "Cold-gas RCS thrusters", count: 8, purpose: "Attitude control, both stages" },
    boosters: { name: "None", count: 0, type: "—", thrustEach: "—" },
    propellant: "Liquid methane / LOX",
    guidance: "Fully autonomous flight computer, real-time engine-out compensation",
    flavor: "Booster and Ship stacked into the tallest rocket ever flown. Ambitious. Loud. Rated for a 'rapid unscheduled disassembly' or two along the way.",
    palette: { hull: "#c9cdd3", hullShadow: "#71767e", accent: "#1c1c1c", trim: "#8b9198", window: "#dfe6ea", flameCore: "#fff8e0", flameOuter: "#4dc7ff" },
    build: { boosters: 0, nose: "blunt", fin: "small", stripes: true, legs: false, gridfins: true, flaps: true },
  },
  {
    id: "soyuz-2",
    name: "Soyuz-2.1a",
    designation: "Roscosmos",
    country: "Russia",
    flag: "🇷🇺",
    env: { time: "night", terrain: "desert", locale: "Baikonur Cosmodrome, Kazakhstan" },
    className: "Medium-lift orbital launch vehicle",
    tagline: "A direct descendant of the most-launched rocket family in history.",
    stages: 3,
    heightM: 46.3,
    diameterM: 10.3,
    liftoffMassT: 312,
    payload: "7,020 kg to LEO",
    primary: { name: "RD-108A", cycle: "Staged-combustion kerolox (core)", count: 1, thrustEach: "792 kN" },
    secondary: { name: "Vernier chambers", count: 12, purpose: "Steering, core + boosters" },
    boosters: { name: "RD-107A strap-ons", count: 4, type: "Liquid strap-on", thrustEach: "838 kN" },
    propellant: "RP-1 / LOX",
    guidance: "Digital flight control system (2.1a upgrade over analog R-7 heritage)",
    flavor: "The four tapered strap-on boosters give it the famous 'Korolev cross' silhouette on separation.",
    palette: { hull: "#eef0e6", hullShadow: "#a9ad9c", accent: "#2f6b3a", trim: "#3f8a4a", window: "#cfe8ff", flameCore: "#fff2b0", flameOuter: "#ff8a3d" },
    build: { boosters: 4, boosterHeightFrac: 0.85, nose: "point", fin: "wide", stripes: true, legs: false, gridfins: false, escapeTower: true },
  },
  {
    id: "long-march-5",
    name: "Long March 5",
    designation: "CASC",
    country: "China",
    flag: "🇨🇳",
    env: { time: "day", terrain: "tropical", locale: "Wenchang, Hainan, China" },
    className: "Heavy-lift orbital launch vehicle",
    tagline: "China's flagship for space-station modules and lunar cargo.",
    stages: 2,
    heightM: 57,
    diameterM: 5,
    liftoffMassT: 869,
    payload: "25,000 kg to LEO",
    primary: { name: "YF-77", cycle: "Gas-generator hydrolox (core)", count: 2, thrustEach: "510 kN" },
    secondary: { name: "Vernier / attitude thrusters", count: 4, purpose: "Core steering" },
    boosters: { name: "YF-100 strap-ons", count: 4, type: "Liquid strap-on (kerolox)", thrustEach: "1,200 kN" },
    propellant: "LH2 / LOX (core), RP-1 / LOX (boosters)",
    guidance: "Domestic inertial guidance, redundant flight computers",
    flavor: "Nicknamed 'Fat Five' for its wide 5-meter core — a big step up from earlier Long March generations.",
    palette: { hull: "#f4f4f0", hullShadow: "#b9bcb4", accent: "#1f4e9c", trim: "#c23b3b", window: "#dff0ff", flameCore: "#fff2b0", flameOuter: "#ff7a3d" },
    build: { boosters: 4, boosterHeightFrac: 0.5, nose: "round", fin: "straight", stripes: true, legs: false, gridfins: false },
  },
  {
    id: "ariane-6",
    name: "Ariane 6",
    designation: "ArianeGroup / ESA",
    country: "Europe",
    flag: "🇪🇺",
    env: { time: "twilight", terrain: "tropical", locale: "Kourou, French Guiana" },
    className: "Medium/heavy-lift orbital launch vehicle",
    tagline: "Europe's newest flagship, successor to Ariane 5.",
    stages: 2,
    heightM: 63,
    diameterM: 5.4,
    liftoffMassT: 530,
    payload: "21,650 kg to LEO (A64 variant)",
    primary: { name: "Vulcain 2.1", cycle: "Gas-generator hydrolox", count: 1, thrustEach: "1,370 kN" },
    secondary: { name: "Vinci restart thrusters", count: 2, purpose: "Upper-stage multiple burns" },
    boosters: { name: "P120C solid strap-ons", count: 4, type: "Solid strap-on", thrustEach: "4,500 kN" },
    propellant: "LH2 / LOX (core), HTPB solid (boosters)",
    guidance: "European inertial navigation, autonomous flight termination",
    flavor: "Built around a shared solid-booster segment used across Europe's rocket family for economies of scale.",
    palette: { hull: "#f6f6f2", hullShadow: "#b7b9b2", accent: "#0b3d91", trim: "#e8c46a", window: "#cfe4ff", flameCore: "#fff2b0", flameOuter: "#ff9a3d" },
    build: { boosters: 4, boosterHeightFrac: 0.42, nose: "point", fin: "sweep", stripes: true, legs: false, gridfins: false },
  },
  {
    id: "h3",
    name: "H3",
    designation: "JAXA / MHI",
    country: "Japan",
    flag: "🇯🇵",
    env: { time: "day", terrain: "alpine", locale: "Tanegashima Space Center, Japan" },
    className: "Medium/heavy-lift orbital launch vehicle",
    tagline: "Built for a faster cadence and a lower price tag.",
    stages: 2,
    heightM: 63,
    diameterM: 5.2,
    liftoffMassT: 574,
    payload: "~6,500 kg to SSO (H3-24 variant)",
    primary: { name: "LE-9", cycle: "Expander-bleed hydrolox", count: 2, thrustEach: "1,471 kN" },
    secondary: { name: "RCS thrusters", count: 4, purpose: "Coast-phase attitude control" },
    boosters: { name: "SRB-3 solid strap-ons", count: 2, type: "Solid strap-on", thrustEach: "2,271 kN" },
    propellant: "LH2 / LOX (core), HTPB solid (boosters)",
    guidance: "JAXA autonomous flight safety system",
    flavor: "Japan's new-generation flagship, replacing the long-serving H-IIA.",
    palette: { hull: "#f2f2ee", hullShadow: "#b3b5ae", accent: "#bc002d", trim: "#5a5a56", window: "#cfe8ff", flameCore: "#fff2b0", flameOuter: "#ff7a3d" },
    build: { boosters: 2, boosterHeightFrac: 0.65, nose: "round", fin: "straight", stripes: true, legs: false, gridfins: false },
  },
  {
    id: "lvm3",
    name: "LVM3",
    designation: "ISRO",
    country: "India",
    flag: "🇮🇳",
    env: { time: "night", terrain: "coastal", locale: "Sriharikota, India" },
    className: "Heavy-lift orbital launch vehicle",
    tagline: "The rocket that sent Chandrayaan-3 to the Moon.",
    stages: 3,
    heightM: 43.5,
    diameterM: 4,
    liftoffMassT: 640,
    payload: "8,000 kg to LEO",
    primary: { name: "Vikas (L110 core)", cycle: "Staged-combustion hypergolic", count: 2, thrustEach: "766 kN" },
    secondary: { name: "Reaction control thrusters", count: 8, purpose: "Coast & orientation control" },
    boosters: { name: "S200 solid strap-ons", count: 2, type: "Solid strap-on", thrustEach: "5,150 kN" },
    propellant: "UH25 / N2O4 (core), HTPB solid (boosters), LH2/LOX (cryogenic upper stage)",
    guidance: "ISRO inertial navigation, redundant onboard computers",
    flavor: "The S200 boosters are among the largest solid rocket motors flying anywhere in the world.",
    palette: { hull: "#f4f4f0", hullShadow: "#b9bcb4", accent: "#ff9933", trim: "#1f2d5c", window: "#dff0ff", flameCore: "#fff2b0", flameOuter: "#ff8a3d" },
    build: { boosters: 2, boosterHeightFrac: 0.7, nose: "blunt", fin: "small", stripes: true, legs: false, gridfins: false },
  },
  {
    id: "nuri",
    name: "Nuri",
    designation: "KARI",
    country: "South Korea",
    flag: "🇰🇷",
    env: { time: "twilight", terrain: "alpine", locale: "Naro Space Center, South Korea" },
    className: "Medium-lift orbital launch vehicle",
    tagline: "South Korea's first fully home-grown launch vehicle.",
    stages: 3,
    heightM: 47.2,
    diameterM: 3.5,
    liftoffMassT: 200,
    payload: "2,600 kg to LEO",
    primary: { name: "KRE-075", cycle: "Gas-generator kerolox, clustered core", count: 4, thrustEach: "735 kN" },
    secondary: { name: "Gimbal / vernier system", count: 4, purpose: "Core steering" },
    boosters: { name: "None", count: 0, type: "—", thrustEach: "—" },
    propellant: "RP-1 / LOX",
    guidance: "Domestically developed inertial guidance",
    flavor: "No strap-on boosters — the four clustered first-stage engines do all the work themselves.",
    palette: { hull: "#f4f4f0", hullShadow: "#b9bcb4", accent: "#003478", trim: "#c23b3b", window: "#cfe4ff", flameCore: "#fff2b0", flameOuter: "#ff9a3d" },
    build: { boosters: 0, nose: "point", fin: "straight", stripes: true, legs: false, gridfins: false },
  },
  {
    id: "electron",
    name: "Electron",
    designation: "Rocket Lab",
    country: "New Zealand / USA",
    flag: "🇳🇿",
    env: { time: "night", terrain: "coastal", locale: "Māhia Peninsula, New Zealand" },
    className: "Light-lift orbital launch vehicle",
    tagline: "Carbon-fiber, battery-fed, and one of the most-flown small rockets around.",
    stages: 2,
    heightM: 18,
    diameterM: 1.2,
    liftoffMassT: 12.5,
    payload: "300 kg to LEO",
    primary: { name: "Rutherford", cycle: "Electric-pump-fed kerolox", count: 9, thrustEach: "24.9 kN" },
    secondary: { name: "Curie kick stage", count: 1, purpose: "Precision orbital insertion" },
    boosters: { name: "None", count: 0, type: "—", thrustEach: "—" },
    propellant: "RP-1 / LOX",
    guidance: "3D-printed engine components; battery-electric turbopumps",
    flavor: "Slender, matte-black, and unusually small next to everything else on this pad — don't let that fool you.",
    palette: { hull: "#2b2b30", hullShadow: "#17171a", accent: "#caa14d", trim: "#4a4a52", window: "#8fd3ff", flameCore: "#fff2b0", flameOuter: "#ff7a3d" },
    build: { boosters: 0, nose: "point", fin: "small", stripes: false, legs: false, gridfins: false, bodyWidthFrac: 0.3 },
  },
  {
    id: "vulcan-centaur",
    name: "Vulcan Centaur",
    designation: "ULA",
    country: "USA",
    flag: "🇺🇸",
    env: { time: "day", terrain: "coastal", locale: "Cape Canaveral, USA" },
    className: "Heavy-lift orbital launch vehicle",
    tagline: "Replaces the Atlas V and Delta IV in one rocket.",
    stages: 2,
    heightM: 61.6,
    diameterM: 5.4,
    liftoffMassT: 546,
    payload: "27,200 kg to LEO",
    primary: { name: "BE-4", cycle: "Staged-combustion methalox", count: 2, thrustEach: "2,400 kN" },
    secondary: { name: "Centaur RL10 engines", count: 2, purpose: "High-energy upper-stage burns" },
    boosters: { name: "GEM 63XL solid strap-ons", count: 4, type: "Solid strap-on", thrustEach: "~1,900 kN" },
    propellant: "LNG / LOX (core), LH2/LOX (Centaur upper stage), HTPB solid (boosters)",
    guidance: "ULA autonomous flight safety, inertial navigation",
    flavor: "First flew in 2024, closing out an era of Atlas and Delta rockets that stretched back to the Cold War.",
    palette: { hull: "#eceef0", hullShadow: "#adb1b8", accent: "#1c2733", trim: "#4a5a6b", window: "#cfe4ff", flameCore: "#fff2b0", flameOuter: "#ff8a3d" },
    build: { boosters: 4, boosterHeightFrac: 0.55, nose: "point", fin: "straight", stripes: true, legs: false, gridfins: false },
  },
];

// 50 cargo-manifest items — plausible launch payload/equipment, so the
// pick feels like a real load-out decision. Each has a small pixel-icon
// spec; icon templates + the 3-color scheme are rendered by drawIcon()
// in pixelart.js — see that file for what each `tpl` looks like.
const ITEMS = [
  { name: "Oxygen tank", icon: { tpl: "cylinder", body: "#eaf0f4", accent: "#5a8ca3", detail: "#2b2b2e" } },
  { name: "Heat shield tile", icon: { tpl: "tile", body: "#e8e2c8", accent: "#2b2b2e", detail: "#8a5a24" } },
  { name: "Parachute pack", icon: { tpl: "chute", body: "#e8756a", accent: "#f2ede1", detail: "#8a3d4a" } },
  { name: "Guidance computer", icon: { tpl: "techbox", body: "#5a5a56", accent: "#8fd3ff", detail: "#2b2b2e", variant: "screen" } },
  { name: "Solar panel array", icon: { tpl: "panel", body: "#1f4e9c", accent: "#5a8ca3", detail: "#e8e2c8" } },
  { name: "Satellite payload", icon: { tpl: "satellite", body: "#e8e2c8", accent: "#1f4e9c", detail: "#8a8680" } },
  { name: "Communications antenna", icon: { tpl: "dish", body: "#e8e2c8", accent: "#8a8680", detail: "#2b2b2e" } },
  { name: "Docking ring", icon: { tpl: "ring", body: "#c9c2a8", accent: "#e8c46a", detail: "#8a8680" } },
  { name: "Robotic arm", icon: { tpl: "arm", body: "#e8e2c8", accent: "#5a5a56", detail: "#2b2b2e" } },
  { name: "Space telescope module", icon: { tpl: "scope", body: "#eaf0f4", accent: "#2b2b2e", detail: "#8fd3ff" } },
  { name: "First aid kit", icon: { tpl: "firstaid", body: "#f2ede1", accent: "#e05a4a", detail: "#2b2b2e" } },
  { name: "CO2 scrubber", icon: { tpl: "techbox", body: "#8a8680", accent: "#7fae4d", detail: "#2b2b2e", variant: "vents" } },
  { name: "Radiation shielding", icon: { tpl: "shieldplates", body: "#8a8680", accent: "#c9c2a8", detail: "#e8c46a" } },
  { name: "Momentum wheel", icon: { tpl: "ring", body: "#3a3a3d", accent: "#8a8680", detail: "#e8c46a", spokes: true } },
  { name: "Star tracker", icon: { tpl: "scope", body: "#3a3a3d", accent: "#8fd3ff", detail: "#e8c46a" } },
  { name: "Backup flight computer", icon: { tpl: "techbox", body: "#5a5a56", accent: "#e8c46a", detail: "#2b2b2e", variant: "screen", blip: true } },
  { name: "Spare fuel canister", icon: { tpl: "cylinder", body: "#e8756a", accent: "#e05a4a", detail: "#2b2b2e" } },
  { name: "Water purifier", icon: { tpl: "purifier", body: "#eaf0f4", accent: "#5a8ca3", detail: "#8fd3ff" } },
  { name: "Thermal blanket", icon: { tpl: "blanket", body: "#c9c2a8", accent: "#e8c46a", detail: "#8a8680" } },
  { name: "Toolkit", icon: { tpl: "toolbox", body: "#e05a4a", accent: "#8a8680", detail: "#2b2b2e" } },
  { name: "Welding torch", icon: { tpl: "horn", body: "#8a8680", accent: "#e8c46a", detail: "#e05a4a" } },
  { name: "Spare bolts & fasteners", icon: { tpl: "bolt", body: "#8a8680", accent: "#c9c2a8", detail: "#2b2b2e" } },
  { name: "Cable reel", icon: { tpl: "tape", body: "#3a3a3d", accent: "#e8c46a", detail: "#2b2b2e" } },
  { name: "GPS module", icon: { tpl: "pin", body: "#e8756a", accent: "#f2ede1", detail: "#2b2b2e" } },
  { name: "3D printer", icon: { tpl: "techbox", body: "#e8e2c8", accent: "#8a8680", detail: "#2b2b2e", variant: "slot" } },
  { name: "Survey drone", icon: { tpl: "drone", body: "#3a3a3d", accent: "#8fd3ff", detail: "#8a8680" } },
  { name: "Seed vault", icon: { tpl: "crate", body: "#8a5a34", accent: "#7fae4d", detail: "#5a3d1f" } },
  { name: "Plant growth experiment", icon: { tpl: "plant", body: "#7fae4d", accent: "#5a9a5a", detail: "#c47a3d" } },
  { name: "Sample containers", icon: { tpl: "vial", body: "#eaf0f4", accent: "#7fae4d", detail: "#8a8680" } },
  { name: "Exercise resistance bands", icon: { tpl: "ring", body: "#e05a4a", accent: "#e8756a", detail: "#8a3d4a", flat: true } },
  { name: "Ration packs", icon: { tpl: "pouch", body: "#c9c2a8", accent: "#8a8680", detail: "#2b2b2e" } },
  { name: "Coffee machine", icon: { tpl: "coffee", body: "#5a5a56", accent: "#8a5a34", detail: "#f2ede1" } },
  { name: "Mission tablet", icon: { tpl: "tablet", body: "#2b2b2e", accent: "#8fd3ff", detail: "#8a8680" } },
  { name: "Camera rig", icon: { tpl: "camera", body: "#3a3a3d", accent: "#8a8680", detail: "#8fd3ff" } },
  { name: "Mission patch", icon: { tpl: "patch", body: "#1f4e9c", accent: "#e8c46a", detail: "#f2ede1" } },
  { name: "National flag", icon: { tpl: "flag", body: "#e05a4a", accent: "#e8e2c8", detail: "#8a8680" } },
  { name: "Time capsule", icon: { tpl: "capsule", body: "#c9c2a8", accent: "#e8c46a", detail: "#8a8680" } },
  { name: "Rubber duck (zero-g indicator)", icon: { tpl: "duck", body: "#ffd23f", accent: "#ff9f1c", detail: "#3a2b1a" } },
  { name: "Spacesuit", icon: { tpl: "suit", body: "#f2ede1", accent: "#8a8680", detail: "#2b2b2e" } },
  { name: "Helmet", icon: { tpl: "helmet", body: "#eaf0f4", accent: "#e8c46a", detail: "#2b2b2e" } },
  { name: "Sunshield", icon: { tpl: "umbrella", body: "#e8c46a", accent: "#f2ede1", detail: "#8a6d1f" } },
  { name: "Habitat module", icon: { tpl: "jar", body: "#eaf0f4", accent: "#8a8680", detail: "#8fd3ff" } },
  { name: "Cargo pallet", icon: { tpl: "pallet", body: "#8a5a34", accent: "#c9c2a8", detail: "#5a3d1f" } },
  { name: "Network router", icon: { tpl: "techbox", body: "#eaf0f4", accent: "#7fae4d", detail: "#2b2b2e", variant: "screen", blip: true } },
  { name: "Battery pack", icon: { tpl: "battery", body: "#e8e2c8", accent: "#3a2b1a", detail: "#c0392b" } },
  { name: "Fire extinguisher", icon: { tpl: "cylinder", body: "#e05a4a", accent: "#f2ede1", detail: "#2b2b2e" } },
  { name: "Air filtration unit", icon: { tpl: "techbox", body: "#8a8680", accent: "#eaf0f4", detail: "#2b2b2e", variant: "vents" } },
  { name: "Navigation charts", icon: { tpl: "paper", body: "#f2ede1", accent: "#5a8ca3", detail: "#2b2b2e" } },
  { name: "Emergency beacon", icon: { tpl: "beacon", body: "#e05a4a", accent: "#f2c66b", detail: "#2b2b2e" } },
  { name: "Ballast weights", icon: { tpl: "weights", body: "#3a3a3d", accent: "#8a8680", detail: "#2b2b2e" } },
];

// Flavor verdicts for the post-flight cargo readout. Purely decorative —
// assigned per item so the report reads consistently across a session.
const CARGO_VERDICTS = [
  "within nominal parameters",
  "unexpectedly aromatic",
  "not FAA approved",
  "filed under 'concerning'",
  "performed better than the rocket",
  "achieved sentience briefly",
  "still under review by legal",
  "exceeded all low expectations",
  "was not, in fact, secured",
  "somehow the most stable part of the mission",
  "flagged by customs",
  "developed a personality mid-flight",
  "requires a debrief of its own",
];

// Outcomes. Every flight resolves to exactly one of these — picked at
// random when the launch sequence begins.
const FAILURE_MODES = [
  {
    id: "pad-rud",
    name: "Pad RUD",
    reportTitle: "MISSION STATUS: RAPID UNSCHEDULED DISASSEMBLY",
    blurb: "Ignition and disassembly occurred within the same half-second. Efficient, in its own way.",
    captions: [
      "T-minus zero.",
      "Ignition confirmed.",
      "...that's not supposed to happen.",
      "Flight Director has left the chat.",
      "Well, it was on the pad. Technically.",
    ],
  },
  {
    id: "leaning-tower",
    name: "Leaning Tower",
    reportTitle: "MISSION STATUS: GANTRY RECLAMATION",
    blurb: "Thrust was confirmed. Verticality was not maintained. The tower did not appreciate the visit.",
    captions: [
      "Liftoff — sort of.",
      "Why is it leaning.",
      "Please stand clear of the tower.",
      "It's hugging the gantry now.",
      "That's one way to end a flight.",
    ],
  },
  {
    id: "pop-fly",
    name: "Pop Fly",
    reportTitle: "MISSION STATUS: EARLY TERMINATION, AIRBORNE",
    blurb: "Clean liftoff. Brief, scenic ascent. Enthusiastic conclusion a few dozen meters up.",
    captions: [
      "We have liftoff!",
      "Looking good, looking good—",
      "Wait.",
      "Telemetry reads 'uh oh.'",
      "That's a new kind of apogee.",
    ],
  },
  {
    id: "corkscrew",
    name: "Corkscrew Special",
    reportTitle: "MISSION STATUS: LOSS OF ATTITUDE CONTROL",
    blurb: "The rocket briefly explored several attitudes it was not designed for, then several more, then the ground.",
    captions: [
      "Guidance is... doing something.",
      "Is it supposed to spin like that?",
      "Vernier thrusters report they are 'trying their best.'",
      "That is not our flight path.",
      "It found the ground. Eventually.",
    ],
  },
  {
    id: "slow-cook",
    name: "The Slow Cook",
    reportTitle: "MISSION STATUS: STRUCTURAL FIRE, PRE-LIFTOFF",
    blurb: "Never actually left the pad. Simply combusted, patiently, over several seconds, in place.",
    captions: [
      "Ignition sequence start.",
      "We have a small fire. A medium fire, now.",
      "It's not leaving. It's just... cooking.",
      "Someone get the hoses.",
      "Still on the pad. Still on fire.",
    ],
  },
  {
    id: "confetti-mode",
    name: "Confetti Mode",
    reportTitle: "MISSION STATUS: STRUCTURAL FAILURE, MULTI-BODY",
    blurb: "Ascent proceeded until the airframe elected, democratically, to become several smaller airframes.",
    captions: [
      "Good ascent profile so far.",
      "Multiple contacts on radar now. That's new.",
      "It's not one rocket anymore.",
      "Debris field looks almost festive.",
      "Everyone's down. Everyone's in pieces.",
    ],
  },
  {
    id: "deadstick",
    name: "Deadstick Return",
    reportTitle: "MISSION STATUS: LOSS OF THRUST, BALLISTIC RETURN",
    blurb: "The engine gave an honest effort, then quietly gave up. Everything that goes up came back down, all at once.",
    captions: [
      "Ascent looking nominal.",
      "Thrust is... tapering.",
      "We have engine-out. Coasting now.",
      "It's coming back down.",
      "Brace for impact. Again.",
    ],
  },
  {
    id: "off-axis",
    name: "Off-Axis",
    reportTitle: "MISSION STATUS: GUIDANCE FAILURE, GROUND IMPACT",
    blurb: "Somewhere past the tower, the flight path stopped being a suggestion and started being a direction. A sideways one.",
    captions: [
      "Climbing steadily.",
      "Slight pitch deviation, standing by.",
      "That deviation is not correcting.",
      "It is now very sideways.",
      "Impact confirmed, well off the pad.",
    ],
  },
];

const GENERIC_CAPTIONS = [
  "Cargo manifest logged: 13 items, no further questions asked.",
  "Weather at the range: calm, clear, unbothered.",
  "Range safety officer sighs audibly.",
  "This is going in the highlight reel either way.",
  "Somewhere, an intern is taking very detailed notes.",
];
