// --- Rules: how a name gets classified. Order matters — first match wins. ---
// `stop: true` means "don't bother listing what's inside this, just total it
// up as one item" — that's what keeps a node_modules folder with 40,000 tiny
// files from turning into 40,000 rows on screen.
const LARGE_FILE_BYTES = 300 * 1024 * 1024;

const RULES = [
  { test: (n) => n === '.Trash' || n === '.Trashes', category: 'Trash', level: 'safe', reason: 'Already in the Trash — safe to empty.', stop: true },
  { test: (n) => n === 'node_modules' || n === 'bower_components', category: 'JS dependencies', level: 'safe', reason: 'Regenerated automatically by running "npm install" again.', stop: true },
  { test: (n) => n === '.venv' || n === 'venv' || n === 'env', category: 'Python virtual environment', level: 'safe', reason: 'Regenerated by recreating the virtual environment and reinstalling.', stop: true },
  { test: (n) => n === '__pycache__' || n === '.pytest_cache' || n === '.mypy_cache' || n === '.ruff_cache', category: 'Python cache', level: 'safe', reason: 'Rebuilt automatically the next time the code runs.', stop: true },
  { test: (n) => n === 'DerivedData', category: 'Xcode build cache', level: 'safe', reason: 'Xcode regenerates this the next time you build a project.', stop: true },
  { test: (n) => n === 'iOS DeviceSupport' || n === 'watchOS DeviceSupport' || n === 'tvOS DeviceSupport', category: 'Old device symbol files', level: 'review', reason: 'Xcode debugging files for a specific OS version on a real device — re-downloaded automatically next time you connect that device, but only if you still develop for it.', stop: true },
  { test: (n) => n === '.npm' || n === '.gradle' || n === '.cocoapods' || n === '.cache', category: 'Package manager cache', level: 'safe', reason: 'Re-downloaded automatically the next time you install packages.', stop: true },
  { test: (n) => n === 'Caches' || n === 'CachedData' || n === 'CacheStorage' || /Cache$/.test(n), category: 'App cache', level: 'safe', reason: "Temporary data an app rebuilds on its own — deleting it just means the app is slightly slower the next time it opens.", stop: true },
  { test: (n) => n === 'DiagnosticReports', category: 'Crash & diagnostic reports', level: 'safe', reason: "Historical crash logs macOS keeps for its own reference — safe to clear, nothing reads them after the fact unless you're actively debugging a crash.", stop: true },
  { test: (n) => n === 'Logs', category: 'Log files', level: 'safe', reason: 'Old app/system log files — apps just start a fresh one next time; nothing relies on the history.', stop: true },
  { test: (n) => n === 'Saved Application State', category: 'Window-restore state', level: 'safe', reason: "Remembers which windows/tabs each app had open — safe to clear, it just means apps won't restore their previous layout next time they launch.", stop: true },
  { test: (n) => n === 'MobileSync', category: 'iPhone/iPad backups', level: 'review', reason: "Old Finder/iTunes device backups — these hide here and can be tens of GB each. Check Finder → your device → Manage Backups before deleting; keep at least your most recent one.", stop: true },
  { test: (n) => n === 'WebKit', category: 'Safari website data', level: 'review', reason: "Safari's per-site storage — closer to \"cookies\" than a disposable cache. Clearing it frees space but signs you out of sites and can lose offline web-app data.", stop: true },
  { test: (n) => n === 'Cookies.binarycookies', category: 'Safari cookies', level: 'review', reason: 'Every saved Safari login in one file — deleting it signs you out of everything. Usually only a few MB, so rarely worth it just for space.' },
  { test: (n) => n === 'Docker.raw' || n === 'Docker.qcow2', category: 'Docker Desktop virtual disk', level: 'review', reason: "Docker Desktop's own virtual disk — grows over time as you pull images. Shrink it from Docker Desktop's settings (Resources → Disk image size) rather than deleting this file directly." },
  { test: (n) => /\.app$/.test(n), category: 'Application', level: 'keep', reason: "Drag it from Applications to the Trash to uninstall — don't delete files inside it directly.", stop: true },
  { test: (n) => /\.photoslibrary$/.test(n), category: 'Photos library', level: 'keep', reason: 'Your photo library — treat as precious.', stop: true },
  { test: (n) => /\.(imovielibrary|fcpbundle)$/.test(n), category: 'Video library', level: 'keep', reason: 'Video editing project data — treat as precious.', stop: true },
  { test: (n) => /\.musiclibrary$/.test(n), category: 'Music library', level: 'keep', reason: 'Your music library — treat as precious.', stop: true },
  { test: (n) => /\.(sparsebundle|dmg|iso)$/i.test(n), category: 'Disk image', level: 'review', reason: 'Often a leftover installer — check whether you still need it.', stop: true },
  { test: (n) => /\.(vmdk|vdi|vhd)$/i.test(n), category: 'Virtual machine disk', level: 'review', reason: 'Large VM disk — keep only if that virtual machine is still in use.', stop: true },
];

function matchRule(name) {
  for (const rule of RULES) {
    if (rule.test(name)) return rule;
  }
  return null;
}

// --- Scanning ---

const stats = { items: 0, skipped: 0 };
let scanTicker = null;

// `onDiscover` is a hook the live scan-in-progress visualization plugs into
// (see the "Live scan visualization" section) — a no-op by default so the
// scan engine has zero cost when nothing is listening. Kept as a single
// swappable function rather than an event bus since there's only ever one
// listener at a time.
let onDiscover = () => {};

async function sumSizeOnly(dirHandle, depth, topName) {
  let total = 0;
  for await (const [name, handle] of dirHandle.entries()) {
    try {
      if (handle.kind === 'file') {
        if (name === '.DS_Store') continue;
        const file = await handle.getFile();
        total += file.size;
        stats.items++;
        onDiscover({ name, size: file.size, flag: null, depth: depth + 1, topName });
      } else {
        total += await sumSizeOnly(handle, depth + 1, topName);
      }
    } catch {
      stats.skipped++;
    }
  }
  return total;
}

async function scanEntry(handle, name, depth, forceFull, topName) {
  if (handle.kind === 'file') {
    if (name === '.DS_Store') return null;
    const file = await handle.getFile();
    stats.items++;
    const rule = matchRule(name);
    let flag = null;
    if (rule) {
      flag = { category: rule.category, level: rule.level, reason: rule.reason };
    } else if (file.size > LARGE_FILE_BYTES) {
      flag = { category: 'Large file', level: 'review', reason: "Big enough to be worth checking — an old installer, export, or backup you may not need." };
    }
    onDiscover({ name, size: file.size, flag, depth, topName });
    return { name, kind: 'file', size: file.size, flag, children: [] };
  }

  const rule = !forceFull ? matchRule(name) : null;
  if (rule && rule.stop) {
    const size = await sumSizeOnly(handle, depth, topName);
    const flag = { category: rule.category, level: rule.level, reason: rule.reason };
    onDiscover({ name, size, flag, depth, topName });
    return { name, kind: 'directory', size, flag, children: [], stopped: true };
  }

  const children = [];
  let size = 0;
  for await (const [childName, childHandle] of handle.entries()) {
    try {
      const childTop = depth === 0 ? childName : topName;
      const node = await scanEntry(childHandle, childName, depth + 1, false, childTop);
      if (node) {
        children.push(node);
        size += node.size;
      }
    } catch {
      stats.skipped++;
    }
  }
  children.sort((a, b) => b.size - a.size);
  const hasFlaggedDescendant = children.some((c) => c.flag || c.hasFlaggedDescendant);
  const dirNode = { name, kind: 'directory', size, flag: rule ? { category: rule.category, level: rule.level, reason: rule.reason } : null, children, hasFlaggedDescendant };
  // Parent pointers are only needed for the sunburst's breadcrumb/zoom-out —
  // set once here rather than re-derived, since nothing else needs to walk
  // upward through the tree.
  children.forEach((c) => { c.parent = dirNode; });
  onDiscover({ name, size, flag: dirNode.flag, depth, topName });
  return dirNode;
}

// --- Formatting ---

function formatBytes(bytes) {
  if (bytes < 1024) return bytes + ' B';
  const units = ['KB', 'MB', 'GB', 'TB'];
  let val = bytes;
  let i = -1;
  do { val /= 1024; i++; } while (val >= 1024 && i < units.length - 1);
  return val.toFixed(val >= 10 || i === 0 ? 0 : 1) + ' ' + units[i];
}

const ICONS = { file: '📄', directory: '📁' };

// --- Rendering ---

let forest = []; // top-level scanned roots
let activeFilter = 'all';

function nodeMatchesFilter(node, filter) {
  if (filter === 'all') return true;
  return node.flag && node.flag.level === filter;
}

function nodeVisibleUnderFilter(node, filter) {
  if (filter === 'all') return true;
  if (nodeMatchesFilter(node, filter)) return true;
  return node.children.some((c) => nodeVisibleUnderFilter(c, filter));
}

function renderNode(node, depth, filter) {
  if (!nodeVisibleUnderFilter(node, filter)) return null;

  const row = document.createElement('div');
  row.className = 'node-row';
  const hasChildren = node.children.length > 0;
  if (hasChildren) row.classList.add('expandable');
  row.style.paddingLeft = 12 + depth * 20 + 'px';

  const caret = document.createElement('span');
  caret.className = 'node-caret';
  caret.textContent = hasChildren ? '▶' : '';
  row.appendChild(caret);

  const icon = document.createElement('span');
  icon.className = 'node-icon';
  icon.textContent = ICONS[node.kind];
  row.appendChild(icon);

  const nameWrap = document.createElement('div');
  nameWrap.className = 'node-name-wrap';
  const nameEl = document.createElement('div');
  nameEl.className = 'node-name';
  nameEl.textContent = node.name + (node.stopped ? ' /' : '');
  nameWrap.appendChild(nameEl);
  if (node.flag) {
    const reasonEl = document.createElement('div');
    reasonEl.className = 'node-reason';
    reasonEl.textContent = node.flag.reason;
    nameWrap.appendChild(reasonEl);
  }
  row.appendChild(nameWrap);

  const verdict = document.createElement('div');
  verdict.className = 'node-verdict';
  if (node.flag) {
    const badge = document.createElement('span');
    badge.className = 'badge badge-' + node.flag.level;
    badge.textContent = node.flag.level === 'safe' ? 'Safe to delete' : node.flag.level === 'review' ? 'Worth a look' : 'Keep';
    verdict.appendChild(badge);
  }
  row.appendChild(verdict);

  const sizeEl = document.createElement('div');
  sizeEl.className = 'node-size';
  sizeEl.textContent = formatBytes(node.size);
  row.appendChild(sizeEl);

  const wrapper = document.createElement('div');
  wrapper.appendChild(row);

  if (hasChildren) {
    const childrenWrap = document.createElement('div');
    childrenWrap.className = 'node-children';
    for (const child of node.children) {
      const childEl = renderNode(child, depth + 1, filter);
      if (childEl) childrenWrap.appendChild(childEl);
    }

    const shouldAutoOpen = filter !== 'all' || (depth < 4 && node.hasFlaggedDescendant);
    if (shouldAutoOpen) {
      childrenWrap.classList.add('open');
      caret.classList.add('open');
    }

    row.addEventListener('click', () => {
      childrenWrap.classList.toggle('open');
      caret.classList.toggle('open');
    });

    wrapper.appendChild(childrenWrap);
  }

  return wrapper;
}

function renderTree() {
  const tree = document.getElementById('tree');
  tree.innerHTML = '';
  for (const root of forest) {
    const el = renderNode(root, 0, activeFilter);
    if (el) tree.appendChild(el);
  }
}

// --- Sunburst ---
// A radial hierarchy chart: rings = folder depth, arc angle = share of the
// parent's size, color = verdict. Chosen over a flat list as the primary
// view because "which branch is way bigger than its siblings" is exactly
// what this shape is good at — precise comparison of close values stays
// the List view's job (see the dataviz skill's guidance on part-to-whole
// charts), which is why that view is kept as an equal, always-available
// alternative rather than being replaced.

const SUNBURST_FILL = { safe: 'var(--fill-safe)', review: 'var(--fill-review)', keep: 'var(--fill-keep)' };
const RING_WIDTH = 40;
const CENTER_RADIUS = 46;
const MAX_RINGS = 4;
const MAX_CHILDREN_PER_RING = 7;

let focusNode = null;

function getSunburstRoot() {
  if (forest.length === 0) return null;
  if (forest.length === 1) return forest[0];
  const total = forest.reduce((sum, r) => sum + r.size, 0);
  const wrapper = { name: 'All scans', size: total, flag: null, children: forest };
  forest.forEach((r) => { r.parent = wrapper; });
  return wrapper;
}

function resetSunburstFocus() {
  focusNode = getSunburstRoot();
}

function fillForNode(node) {
  if (node.flag) return SUNBURST_FILL[node.flag.level] || 'var(--fill-neutral)';
  return 'var(--fill-neutral)';
}

function polarToXY(cx, cy, r, angle) {
  return [cx + r * Math.cos(angle), cy + r * Math.sin(angle)];
}

function arcPath(cx, cy, innerR, outerR, a0, a1) {
  const largeArc = a1 - a0 > Math.PI ? 1 : 0;
  const [x1, y1] = polarToXY(cx, cy, outerR, a0);
  const [x2, y2] = polarToXY(cx, cy, outerR, a1);
  const [x3, y3] = polarToXY(cx, cy, innerR, a1);
  const [x4, y4] = polarToXY(cx, cy, innerR, a0);
  return `M ${x1} ${y1} A ${outerR} ${outerR} 0 ${largeArc} 1 ${x2} ${y2} L ${x3} ${y3} A ${innerR} ${innerR} 0 ${largeArc} 0 ${x4} ${y4} Z`;
}

function layoutRing(node, depth, a0, a1, out) {
  if (depth > MAX_RINGS || !node.children || node.children.length === 0) return;
  const kids = node.children.filter((c) => c.size > 0).sort((a, b) => b.size - a.size);
  let shown = kids;
  let otherSize = 0;
  let otherCount = 0;
  if (kids.length > MAX_CHILDREN_PER_RING) {
    shown = kids.slice(0, MAX_CHILDREN_PER_RING - 1);
    const rest = kids.slice(MAX_CHILDREN_PER_RING - 1);
    otherCount = rest.length;
    otherSize = rest.reduce((sum, c) => sum + c.size, 0);
  }
  const total = node.size || 1;
  const innerR = CENTER_RADIUS + (depth - 1) * RING_WIDTH;
  const outerR = CENTER_RADIUS + depth * RING_WIDTH;
  let cursor = a0;
  for (const child of shown) {
    const span = (child.size / total) * (a1 - a0);
    const seg = { node: child, a0: cursor, a1: cursor + span, innerR, outerR, isOther: false };
    out.push(seg);
    layoutRing(child, depth + 1, seg.a0, seg.a1, out);
    cursor = seg.a1;
  }
  if (otherCount > 0) {
    const span = (otherSize / total) * (a1 - a0);
    out.push({
      node: { name: `+${otherCount} smaller item${otherCount === 1 ? '' : 's'}`, size: otherSize, flag: null, children: [] },
      a0: cursor,
      a1: cursor + span,
      innerR,
      outerR,
      isOther: true,
    });
  }
}

function showTooltip(evt, node) {
  const box = document.getElementById('tooltip');
  box.innerHTML = '';
  const nameEl = document.createElement('div');
  nameEl.className = 'tooltip-name';
  nameEl.textContent = node.name;
  const sizeEl = document.createElement('div');
  sizeEl.className = 'tooltip-size';
  sizeEl.textContent = formatBytes(node.size);
  box.appendChild(nameEl);
  box.appendChild(sizeEl);
  if (node.flag) {
    const badge = document.createElement('div');
    badge.className = 'badge badge-' + node.flag.level + ' tooltip-badge';
    badge.textContent = node.flag.level === 'safe' ? 'Safe to delete' : node.flag.level === 'review' ? 'Worth a look' : 'Keep';
    box.appendChild(badge);
    const reason = document.createElement('div');
    reason.className = 'tooltip-reason';
    reason.textContent = node.flag.reason;
    box.appendChild(reason);
  }
  box.hidden = false;
  let x, y;
  if (evt.type === 'focus') {
    const r = evt.target.getBoundingClientRect();
    x = r.left + r.width / 2;
    y = r.top - 8;
  } else {
    x = evt.clientX + 16;
    y = evt.clientY + 16;
  }
  box.style.left = x + 'px';
  box.style.top = y + 'px';
}

function hideTooltip() {
  document.getElementById('tooltip').hidden = true;
}

function zoomTo(node) {
  focusNode = node;
  renderSunburst();
}

function renderCenter() {
  const el = document.getElementById('sunburstCenter');
  el.innerHTML = '';
  const nameEl = document.createElement('div');
  nameEl.className = 'sunburst-center-name';
  nameEl.textContent = focusNode.name;
  const sizeEl = document.createElement('div');
  sizeEl.className = 'sunburst-center-size';
  sizeEl.textContent = formatBytes(focusNode.size);
  el.appendChild(nameEl);
  el.appendChild(sizeEl);
  if (focusNode.parent) {
    el.classList.add('clickable');
    el.title = 'Zoom out';
    el.onclick = () => zoomTo(focusNode.parent);
  } else {
    el.classList.remove('clickable');
    el.onclick = null;
    el.title = '';
  }
}

function renderBreadcrumb() {
  const el = document.getElementById('breadcrumb');
  el.innerHTML = '';
  const chain = [];
  for (let n = focusNode; n; n = n.parent) chain.unshift(n);
  chain.forEach((node, i) => {
    const isLast = i === chain.length - 1;
    const btn = document.createElement('button');
    btn.type = 'button';
    btn.className = 'crumb' + (isLast ? ' crumb-current' : '');
    btn.textContent = node.name;
    if (isLast) {
      btn.disabled = true;
    } else {
      btn.addEventListener('click', () => zoomTo(node));
    }
    el.appendChild(btn);
    if (!isLast) {
      const sep = document.createElement('span');
      sep.className = 'crumb-sep';
      sep.textContent = '›';
      el.appendChild(sep);
    }
  });
}

function renderSunburst() {
  const svg = document.getElementById('sunburstSvg');
  svg.innerHTML = '';
  if (!focusNode) return;

  const cx = 260, cy = 260;
  const segments = [];
  layoutRing(focusNode, 1, -Math.PI / 2, -Math.PI / 2 + Math.PI * 2, segments);

  const ns = 'http://www.w3.org/2000/svg';
  for (const seg of segments) {
    const path = document.createElementNS(ns, 'path');
    path.setAttribute('d', arcPath(cx, cy, seg.innerR, seg.outerR, seg.a0, seg.a1));
    path.setAttribute('class', 'sunburst-arc' + (seg.isOther ? ' sunburst-arc-other' : ''));
    path.style.fill = fillForNode(seg.node);

    if (activeFilter !== 'all' && !(seg.node.flag && seg.node.flag.level === activeFilter)) {
      path.classList.add('dimmed');
    }

    const canZoom = !seg.isOther && seg.node.children && seg.node.children.length > 0;
    if (canZoom) {
      path.classList.add('clickable');
      path.tabIndex = 0;
      path.setAttribute('role', 'button');
      path.setAttribute('aria-label', `${seg.node.name}, ${formatBytes(seg.node.size)}, zoom in`);
      path.addEventListener('click', () => zoomTo(seg.node));
      path.addEventListener('keydown', (e) => {
        if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); zoomTo(seg.node); }
      });
    }
    path.addEventListener('pointermove', (e) => showTooltip(e, seg.node));
    path.addEventListener('pointerleave', hideTooltip);
    path.addEventListener('focus', (e) => showTooltip(e, seg.node));
    path.addEventListener('blur', hideTooltip);
    svg.appendChild(path);
  }

  renderCenter();
  renderBreadcrumb();
}

function sumByLevel(node, level) {
  let total = 0;
  if (node.flag && node.flag.level === level) return node.size;
  for (const child of node.children) total += sumByLevel(child, level);
  return total;
}

function renderSummary() {
  const totalScanned = forest.reduce((sum, r) => sum + r.size, 0);
  const safeTotal = forest.reduce((sum, r) => sum + sumByLevel(r, 'safe'), 0);
  const reviewTotal = forest.reduce((sum, r) => sum + sumByLevel(r, 'review'), 0);

  document.getElementById('statTotal').textContent = formatBytes(totalScanned);
  document.getElementById('statSafe').textContent = formatBytes(safeTotal);
  document.getElementById('statReview').textContent = formatBytes(reviewTotal);
  document.getElementById('statItems').textContent = stats.items.toLocaleString();

  const skippedNote = document.getElementById('skippedNote');
  if (stats.skipped > 0) {
    skippedNote.hidden = false;
    skippedNote.textContent = `${stats.skipped.toLocaleString()} item(s) couldn't be read (permission denied) and were skipped.`;
  } else {
    skippedNote.hidden = true;
  }
}

function updateProgressText() {
  document.getElementById('progressText').textContent =
    `Scanning… ${stats.items.toLocaleString()} items found`;
}

// --- Live scan visualization ---
// A radial "hub and spoke" particle show, one bubble per file/folder as
// `onDiscover` reports it, drawn on <canvas> rather than SVG/DOM. This is
// pure spectacle for while a scan is running — not the source of truth
// (the Sunburst/List views are, once the scan finishes) — which is what
// lets it take liberties a real chart couldn't: bubble position is a
// deliberately approximate hash of "which top-level folder is this under"
// plus jitter, not an exact parent-child layout, and old/uninteresting
// bubbles get evicted once a real scan's item count (which routinely runs
// into six figures for a home folder) would otherwise overwhelm the canvas.
// Decoupling discovery from rendering — `onDiscover` just pushes onto
// `liveQueue`, a separate rAF loop drains it — is what keeps the scan
// itself fast: it never waits on a frame.

const LIVE_MAX_RINGS = 6;
const LIVE_NODE_CAP = 1400;
const LIVE_QUEUE_CAP = 3000;
const LIVE_DRAIN_PER_FRAME = 50;
const LIVE_GOLDEN_ANGLE = Math.PI * (3 - Math.sqrt(5));
const LIVE_COLORS = { safe: '#009c5c', review: '#b37900', keep: '#4b79c8' };
const LIVE_NEUTRAL = '#4a4a5c';

let liveQueue = [];
let liveNodes = [];
let liveSectorAngles = new Map();
let liveRotation = 0;
let liveRafId = null;
let liveVizActive = false;

function sectorAngleFor(name) {
  if (!liveSectorAngles.has(name)) {
    liveSectorAngles.set(name, liveSectorAngles.size * LIVE_GOLDEN_ANGLE);
  }
  return liveSectorAngles.get(name);
}

function sizeToLiveRadius(bytes) {
  if (bytes <= 0) return 1.5;
  return Math.min(16, Math.max(1.5, Math.log2(bytes + 1) * 0.8));
}

function spawnLiveNode(item) {
  const ring = Math.min(Math.max(item.depth, 1), LIVE_MAX_RINGS);
  const baseAngle = sectorAngleFor(item.topName || item.name);
  const spread = (Math.PI / 5) * (ring / LIVE_MAX_RINGS) + Math.PI / 24;
  liveNodes.push({
    name: item.name,
    size: item.size,
    flag: item.flag,
    ring,
    angle: baseAngle + (Math.random() - 0.5) * spread,
    jitterR: (Math.random() - 0.5) * 0.6,
    r: sizeToLiveRadius(item.size),
    color: item.flag ? LIVE_COLORS[item.flag.level] || LIVE_NEUTRAL : LIVE_NEUTRAL,
    born: performance.now(),
    x: 0,
    y: 0,
  });
  if (liveNodes.length > LIVE_NODE_CAP) {
    let idx = liveNodes.findIndex((n) => !n.flag);
    if (idx === -1) idx = 0;
    liveNodes.splice(idx, 1);
  }
}

function resizeLiveCanvas() {
  const canvas = document.getElementById('liveCanvas');
  const rect = canvas.getBoundingClientRect();
  if (rect.width === 0) return;
  const dpr = window.devicePixelRatio || 1;
  canvas.width = rect.width * dpr;
  canvas.height = rect.height * dpr;
}

function liveFrame(ts) {
  let drained = 0;
  while (drained < LIVE_DRAIN_PER_FRAME && liveQueue.length) {
    spawnLiveNode(liveQueue.shift());
    drained++;
  }

  const canvas = document.getElementById('liveCanvas');
  const ctx = canvas.getContext('2d');
  const w = canvas.width, h = canvas.height;
  ctx.clearRect(0, 0, w, h);

  const size = Math.min(w, h);
  const maxR = size * 0.46;
  const hubR = size * 0.07;
  const ringStep = (maxR - hubR) / LIVE_MAX_RINGS;

  liveRotation += 0.0009;

  ctx.save();
  ctx.translate(w / 2, h / 2);
  ctx.rotate(liveRotation);

  ctx.strokeStyle = 'rgba(255,255,255,0.05)';
  ctx.lineWidth = 1;
  for (let i = 1; i <= LIVE_MAX_RINGS; i++) {
    ctx.beginPath();
    ctx.arc(0, 0, hubR + i * ringStep, 0, Math.PI * 2);
    ctx.stroke();
  }

  for (const node of liveNodes) {
    const radius = hubR + node.ring * ringStep + node.jitterR * ringStep;
    const x = radius * Math.cos(node.angle);
    const y = radius * Math.sin(node.angle);
    node.x = x;
    node.y = y;

    const innerRadius = hubR + (node.ring - 1) * ringStep;
    ctx.strokeStyle = node.color + '55';
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(innerRadius * Math.cos(node.angle), innerRadius * Math.sin(node.angle));
    ctx.lineTo(x, y);
    ctx.stroke();

    const grow = Math.min(1, (ts - node.born) / 260);
    ctx.beginPath();
    ctx.fillStyle = node.color;
    ctx.globalAlpha = 0.85 * grow;
    ctx.shadowColor = node.color;
    ctx.shadowBlur = node.flag ? 8 : 3;
    ctx.arc(x, y, node.r * grow, 0, Math.PI * 2);
    ctx.fill();
    ctx.shadowBlur = 0;
    ctx.globalAlpha = 1;
  }

  const pulse = 1 + Math.sin(ts / 400) * 0.06;
  ctx.beginPath();
  ctx.fillStyle = '#e8e8ec';
  ctx.shadowColor = '#6f9ff2';
  ctx.shadowBlur = 18;
  ctx.arc(0, 0, hubR * pulse, 0, Math.PI * 2);
  ctx.fill();
  ctx.shadowBlur = 0;

  ctx.restore();

  if (liveVizActive) liveRafId = requestAnimationFrame(liveFrame);
}

function startLiveViz() {
  liveNodes = [];
  liveQueue = [];
  liveSectorAngles = new Map();
  liveRotation = 0;
  liveVizActive = true;
  onDiscover = (item) => {
    liveQueue.push(item);
    if (liveQueue.length > LIVE_QUEUE_CAP) liveQueue.splice(0, liveQueue.length - LIVE_QUEUE_CAP);
  };
  resizeLiveCanvas();
  liveRafId = requestAnimationFrame(liveFrame);
}

function stopLiveViz() {
  liveVizActive = false;
  onDiscover = () => {};
  if (liveRafId) cancelAnimationFrame(liveRafId);
  liveRafId = null;
  liveNodes = [];
  liveQueue = [];
}

function liveHitTest(clientX, clientY) {
  const canvas = document.getElementById('liveCanvas');
  const rect = canvas.getBoundingClientRect();
  const dpr = window.devicePixelRatio || 1;
  const mx = (clientX - rect.left) * dpr - canvas.width / 2;
  const my = (clientY - rect.top) * dpr - canvas.height / 2;
  const cosR = Math.cos(-liveRotation), sinR = Math.sin(-liveRotation);
  const lx = mx * cosR - my * sinR;
  const ly = mx * sinR + my * cosR;
  let hit = null, hitDist = Infinity;
  for (const node of liveNodes) {
    const d = Math.hypot(lx - node.x, ly - node.y);
    const hitR = Math.max(node.r, 6) + 3;
    if (d <= hitR && d < hitDist) {
      hit = node;
      hitDist = d;
    }
  }
  return hit;
}

document.getElementById('liveCanvas').addEventListener('pointermove', (e) => {
  const hit = liveHitTest(e.clientX, e.clientY);
  if (hit) showTooltip(e, hit);
  else hideTooltip();
});
document.getElementById('liveCanvas').addEventListener('pointerleave', hideTooltip);
window.addEventListener('resize', () => { if (liveVizActive) resizeLiveCanvas(); });

// --- Wiring ---

function showError(err) {
  const box = document.getElementById('errorNotice');
  if (location.protocol === 'file:') {
    box.textContent = "This can't run when the page is opened directly as a file (the address bar shows file://) — Chrome blocks folder access there for security. Serve this folder locally instead: open Terminal, cd into this folder, run \"python3 -m http.server\", then visit http://localhost:8000 in Chrome. (The version hosted on GitHub Pages, once pushed, won't have this problem.)";
  } else {
    box.textContent = 'Something went wrong: ' + (err && err.message ? err.message : String(err));
  }
  box.hidden = false;
}

async function runScan(startIn) {
  const supported = 'showDirectoryPicker' in window;
  if (!supported) {
    document.getElementById('unsupported').hidden = false;
    return;
  }
  document.getElementById('errorNotice').hidden = true;

  let handle;
  try {
    // `startIn` only points the OS dialog's starting folder — it grants no
    // access by itself. The user still has to pick and confirm a folder,
    // same as any other call.
    handle = await window.showDirectoryPicker(startIn ? { startIn } : undefined);
  } catch (err) {
    if (err && err.name === 'AbortError') return; // user cancelled the picker
    showError(err);
    return;
  }

  document.getElementById('progress').hidden = false;
  document.getElementById('scanBtn').disabled = true;
  scanTicker = setInterval(updateProgressText, 150);
  startLiveViz();

  try {
    const root = await scanEntry(handle, handle.name, 0, true, handle.name);
    forest.push(root);
    forest.sort((a, b) => b.size - a.size);

    document.getElementById('intro').hidden = true;
    document.getElementById('results').hidden = false;
    renderSummary();
    renderTree();
    resetSunburstFocus();
    renderSunburst();
  } catch (err) {
    showError(err);
  } finally {
    clearInterval(scanTicker);
    stopLiveViz();
    document.getElementById('progress').hidden = true;
    document.getElementById('scanBtn').disabled = false;
  }
}

document.getElementById('scanBtn').addEventListener('click', () => runScan());
document.getElementById('scanAppsBtn').addEventListener('click', () => runScan());
document.getElementById('scanLibraryBtn').addEventListener('click', () => runScan());
document.getElementById('scanAnotherBtn').addEventListener('click', () => runScan());
document.querySelectorAll('.btn-chip').forEach((btn) => {
  btn.addEventListener('click', () => runScan(btn.dataset.startin));
});

document.querySelectorAll('.filter-pill').forEach((pill) => {
  pill.addEventListener('click', () => {
    document.querySelectorAll('.filter-pill').forEach((p) => p.classList.remove('active'));
    pill.classList.add('active');
    activeFilter = pill.dataset.filter;
    renderTree();
    renderSunburst();
  });
});

document.querySelectorAll('.view-tab').forEach((tab) => {
  tab.addEventListener('click', () => {
    document.querySelectorAll('.view-tab').forEach((t) => {
      t.classList.remove('active');
      t.setAttribute('aria-selected', 'false');
    });
    tab.classList.add('active');
    tab.setAttribute('aria-selected', 'true');
    const view = tab.dataset.view;
    document.getElementById('sunburstView').hidden = view !== 'sunburst';
    document.getElementById('listView').hidden = view !== 'list';
  });
});

if (!('showDirectoryPicker' in window)) {
  document.getElementById('unsupported').hidden = false;
  document.getElementById('scanBtn').disabled = true;
}
