// --- Rules: how a name gets classified. Order matters — first match wins. ---
// `stop: true` means "don't bother listing what's inside this, just total it
// up as one item" — that's what keeps a node_modules folder with 40,000 tiny
// files from turning into 40,000 rows on screen.
const LARGE_FILE_BYTES = 300 * 1024 * 1024;

const RULES = [
  { test: (n) => n === '.Trash' || n === '.Trashes', category: 'Trash', level: 'safe', reason: 'Already in the Trash — safe to empty.', stop: true },
  { test: (n) => n === 'node_modules' || n === 'bower_components', category: 'JS dependencies', level: 'safe', reason: 'Regenerated automatically by running "npm install" again.', stop: true },
  { test: (n) => n === '.venv' || n === 'venv' || n === 'env', category: 'Python virtual environment', level: 'safe', reason: 'Regenerated by recreating the virtual environment and reinstalling.', stop: true },
  { test: (n) => n === '__pycache__' || n === '.pytest_cache' || n === '.mypy_cache' || n === '.ruff_cache', category: 'Python cache', level: 'safe', reason: 'Rebuilt automatically the next time the code runs.', stop: true },
  { test: (n) => n === 'DerivedData', category: 'Xcode build cache', level: 'safe', reason: 'Xcode regenerates this the next time you build a project.', stop: true },
  { test: (n) => n === 'iOS DeviceSupport' || n === 'watchOS DeviceSupport' || n === 'tvOS DeviceSupport', category: 'Old device symbol files', level: 'review', reason: 'Xcode debugging files for a specific OS version on a real device — re-downloaded automatically next time you connect that device, but only if you still develop for it.', stop: true },
  { test: (n) => n === '.npm' || n === '.gradle' || n === '.cocoapods' || n === '.cache', category: 'Package manager cache', level: 'safe', reason: 'Re-downloaded automatically the next time you install packages.', stop: true },
  { test: (n) => n === 'Caches' || n === 'CachedData' || n === 'CacheStorage' || /Cache$/.test(n), category: 'App cache', level: 'safe', reason: "Temporary data an app rebuilds on its own — deleting it just means the app is slightly slower the next time it opens.", stop: true },
  { test: (n) => n === 'DiagnosticReports', category: 'Crash & diagnostic reports', level: 'safe', reason: "Historical crash logs macOS keeps for its own reference — safe to clear, nothing reads them after the fact unless you're actively debugging a crash.", stop: true },
  { test: (n) => n === 'Logs', category: 'Log files', level: 'safe', reason: 'Old app/system log files — apps just start a fresh one next time; nothing relies on the history.', stop: true },
  { test: (n) => n === 'Saved Application State', category: 'Window-restore state', level: 'safe', reason: "Remembers which windows/tabs each app had open — safe to clear, it just means apps won't restore their previous layout next time they launch.", stop: true },
  { test: (n) => n === 'MobileSync', category: 'iPhone/iPad backups', level: 'review', reason: "Old Finder/iTunes device backups — these hide here and can be tens of GB each. Check Finder → your device → Manage Backups before deleting; keep at least your most recent one.", stop: true },
  { test: (n) => n === 'WebKit', category: 'Safari website data', level: 'review', reason: "Safari's per-site storage — closer to \"cookies\" than a disposable cache. Clearing it frees space but signs you out of sites and can lose offline web-app data.", stop: true },
  { test: (n) => n === 'Cookies.binarycookies', category: 'Safari cookies', level: 'review', reason: 'Every saved Safari login in one file — deleting it signs you out of everything. Usually only a few MB, so rarely worth it just for space.' },
  { test: (n) => n === 'Docker.raw' || n === 'Docker.qcow2', category: 'Docker Desktop virtual disk', level: 'review', reason: "Docker Desktop's own virtual disk — grows over time as you pull images. Shrink it from Docker Desktop's settings (Resources → Disk image size) rather than deleting this file directly." },
  { test: (n) => /\.app$/.test(n), category: 'Application', level: 'keep', reason: "Drag it from Applications to the Trash to uninstall — don't delete files inside it directly.", stop: true },
  { test: (n) => /\.photoslibrary$/.test(n), category: 'Photos library', level: 'keep', reason: 'Your photo library — treat as precious.', stop: true },
  { test: (n) => /\.(imovielibrary|fcpbundle)$/.test(n), category: 'Video library', level: 'keep', reason: 'Video editing project data — treat as precious.', stop: true },
  { test: (n) => /\.musiclibrary$/.test(n), category: 'Music library', level: 'keep', reason: 'Your music library — treat as precious.', stop: true },
  { test: (n) => /\.(sparsebundle|dmg|iso)$/i.test(n), category: 'Disk image', level: 'review', reason: 'Often a leftover installer — check whether you still need it.', stop: true },
  { test: (n) => /\.(vmdk|vdi|vhd)$/i.test(n), category: 'Virtual machine disk', level: 'review', reason: 'Large VM disk — keep only if that virtual machine is still in use.', stop: true },
];

function matchRule(name) {
  for (const rule of RULES) {
    if (rule.test(name)) return rule;
  }
  return null;
}

// --- Scanning ---

const stats = { items: 0, skipped: 0 };
let scanTicker = null;

// `onDiscover` is a hook the live scan-in-progress visualization plugs into
// (see the "Live scan visualization" section) — a no-op by default so the
// scan engine has zero cost when nothing is listening. Kept as a single
// swappable function rather than an event bus since there's only ever one
// listener at a time.
let onDiscover = () => {};

async function sumSizeOnly(dirHandle, depth, topName) {
  let total = 0;
  for await (const [name, handle] of dirHandle.entries()) {
    try {
      if (handle.kind === 'file') {
        if (name === '.DS_Store') continue;
        const file = await handle.getFile();
        total += file.size;
        stats.items++;
        onDiscover({ name, size: file.size, flag: null, depth: depth + 1, topName });
      } else {
        total += await sumSizeOnly(handle, depth + 1, topName);
      }
    } catch {
      stats.skipped++;
    }
  }
  return total;
}

async function scanEntry(handle, name, depth, forceFull, topName) {
  if (handle.kind === 'file') {
    if (name === '.DS_Store') return null;
    const file = await handle.getFile();
    stats.items++;
    const rule = matchRule(name);
    let flag = null;
    if (rule) {
      flag = { category: rule.category, level: rule.level, reason: rule.reason };
    } else if (file.size > LARGE_FILE_BYTES) {
      flag = { category: 'Large file', level: 'review', reason: "Big enough to be worth checking — an old installer, export, or backup you may not need." };
    }
    onDiscover({ name, size: file.size, flag, depth, topName });
    return { name, kind: 'file', size: file.size, flag, children: [] };
  }

  const rule = !forceFull ? matchRule(name) : null;
  if (rule && rule.stop) {
    const size = await sumSizeOnly(handle, depth, topName);
    const flag = { category: rule.category, level: rule.level, reason: rule.reason };
    onDiscover({ name, size, flag, depth, topName });
    return { name, kind: 'directory', size, flag, children: [], stopped: true };
  }

  const children = [];
  let size = 0;
  for await (const [childName, childHandle] of handle.entries()) {
    try {
      const childTop = depth === 0 ? childName : topName;
      const node = await scanEntry(childHandle, childName, depth + 1, false, childTop);
      if (node) {
        children.push(node);
        size += node.size;
      }
    } catch {
      stats.skipped++;
    }
  }
  children.sort((a, b) => b.size - a.size);
  const hasFlaggedDescendant = children.some((c) => c.flag || c.hasFlaggedDescendant);
  const dirNode = { name, kind: 'directory', size, flag: rule ? { category: rule.category, level: rule.level, reason: rule.reason } : null, children, hasFlaggedDescendant };
  onDiscover({ name, size, flag: dirNode.flag, depth, topName });
  return dirNode;
}

// --- Formatting ---

function formatBytes(bytes) {
  if (bytes < 1024) return bytes + ' B';
  const units = ['KB', 'MB', 'GB', 'TB'];
  let val = bytes;
  let i = -1;
  do { val /= 1024; i++; } while (val >= 1024 && i < units.length - 1);
  return val.toFixed(val >= 10 || i === 0 ? 0 : 1) + ' ' + units[i];
}

const ICONS = { file: '📄', directory: '📁' };

// --- Rendering ---

let forest = []; // top-level scanned roots
let activeFilter = 'all';

function nodeMatchesFilter(node, filter) {
  if (filter === 'all') return true;
  return node.flag && node.flag.level === filter;
}

function nodeVisibleUnderFilter(node, filter) {
  if (filter === 'all') return true;
  if (nodeMatchesFilter(node, filter)) return true;
  return node.children.some((c) => nodeVisibleUnderFilter(c, filter));
}

function renderNode(node, depth, filter) {
  if (!nodeVisibleUnderFilter(node, filter)) return null;

  const row = document.createElement('div');
  row.className = 'node-row';
  const hasChildren = node.children.length > 0;
  if (hasChildren) row.classList.add('expandable');
  row.style.paddingLeft = 12 + depth * 20 + 'px';

  const caret = document.createElement('span');
  caret.className = 'node-caret';
  caret.textContent = hasChildren ? '▶' : '';
  row.appendChild(caret);

  const icon = document.createElement('span');
  icon.className = 'node-icon';
  icon.textContent = ICONS[node.kind];
  row.appendChild(icon);

  const nameWrap = document.createElement('div');
  nameWrap.className = 'node-name-wrap';
  const nameEl = document.createElement('div');
  nameEl.className = 'node-name';
  nameEl.textContent = node.name + (node.stopped ? ' /' : '');
  nameWrap.appendChild(nameEl);
  if (node.flag) {
    const reasonEl = document.createElement('div');
    reasonEl.className = 'node-reason';
    reasonEl.textContent = node.flag.reason;
    nameWrap.appendChild(reasonEl);
  }
  row.appendChild(nameWrap);

  const verdict = document.createElement('div');
  verdict.className = 'node-verdict';
  if (node.flag) {
    const badge = document.createElement('span');
    badge.className = 'badge badge-' + node.flag.level;
    badge.textContent = node.flag.level === 'safe' ? 'Safe to delete' : node.flag.level === 'review' ? 'Worth a look' : 'Keep';
    verdict.appendChild(badge);
  }
  row.appendChild(verdict);

  const sizeEl = document.createElement('div');
  sizeEl.className = 'node-size';
  sizeEl.textContent = formatBytes(node.size);
  row.appendChild(sizeEl);

  const wrapper = document.createElement('div');
  wrapper.appendChild(row);

  if (hasChildren) {
    const childrenWrap = document.createElement('div');
    childrenWrap.className = 'node-children';
    for (const child of node.children) {
      const childEl = renderNode(child, depth + 1, filter);
      if (childEl) childrenWrap.appendChild(childEl);
    }

    const shouldAutoOpen = filter !== 'all' || (depth < 4 && node.hasFlaggedDescendant);
    if (shouldAutoOpen) {
      childrenWrap.classList.add('open');
      caret.classList.add('open');
    }

    row.addEventListener('click', () => {
      childrenWrap.classList.toggle('open');
      caret.classList.toggle('open');
    });

    wrapper.appendChild(childrenWrap);
  }

  return wrapper;
}

function renderTree() {
  const tree = document.getElementById('tree');
  tree.innerHTML = '';
  for (const root of forest) {
    const el = renderNode(root, 0, activeFilter);
    if (el) tree.appendChild(el);
  }
}

// --- Tesseract engine (shared math, used by both the live scan-in-progress
// show and the after-scan results view) ---
// A real rotating 4D hypercube — 16 vertices (every combination of ±1 in 4
// axes), 32 edges (any two vertices differing in exactly one axis) — chosen
// over the earlier sunburst because a literal tesseract was asked for by
// name, "extremely detailed," in the same spirit as Idle Cosmos's
// piece-by-piece cosmic build-up. It replaces the sunburst as the results
// view too (see `buildResultsTesseract`) rather than living only in the
// scan-in-progress show. The List view remains the one place with a fully
// precise, fully recursive breakdown — the dataviz skill's "a table view
// always exists" rule — since a tesseract's vertices are a fixed 16 slots,
// not an arbitrarily-deep hierarchy the way sunburst arcs were.

const TESS_COLORS = { safe: '#009c5c', review: '#b37900', keep: '#4b79c8' };
const TESS_NEUTRAL = '#3a3a46'; // matches --fill-neutral in style.css's legend swatch

function tessColorFor(node) {
  if (node && node.flag) return TESS_COLORS[node.flag.level] || TESS_NEUTRAL;
  return TESS_NEUTRAL;
}

const TESS_VERTS = [];
for (let vi = 0; vi < 16; vi++) {
  TESS_VERTS.push([(vi & 1) ? 1 : -1, (vi & 2) ? 1 : -1, (vi & 4) ? 1 : -1, (vi & 8) ? 1 : -1]);
}
const TESS_EDGES = [];
for (let a = 0; a < 16; a++) {
  for (let b = a + 1; b < 16; b++) {
    const diff = a ^ b;
    if (diff && (diff & (diff - 1)) === 0) TESS_EDGES.push([a, b]);
  }
}
// The order items appear in during a staged reveal: every vertex first,
// then edges sorted so one never appears before both its endpoints have —
// otherwise a "growing" tesseract would show floating lines with no ends.
const TESS_BUILD_ORDER = [
  ...TESS_VERTS.map((_, i) => ({ type: 'vertex', i })),
  ...TESS_EDGES.slice()
    .sort((e1, e2) => Math.max(...e1) - Math.max(...e2) || Math.min(...e1) - Math.min(...e2))
    .map(([a, b]) => ({ type: 'edge', a, b })),
];

function rotate4D(p, angleXW, angleYZ, angleXY) {
  let [x, y, z, w] = p;
  const nx = x * Math.cos(angleXW) - w * Math.sin(angleXW);
  const nw = x * Math.sin(angleXW) + w * Math.cos(angleXW);
  const ny = y * Math.cos(angleYZ) - z * Math.sin(angleYZ);
  const nz = y * Math.sin(angleYZ) + z * Math.cos(angleYZ);
  x = nx; w = nw; y = ny; z = nz;
  const fx = x * Math.cos(angleXY) - y * Math.sin(angleXY);
  const fy = x * Math.sin(angleXY) + y * Math.cos(angleXY);
  return [fx, fy, z, w];
}

function project4D(p, wDist, zDist) {
  const [x, y, z, w] = p;
  const wf = wDist / (wDist - w);
  const x3 = x * wf, y3 = y * wf, z3 = z * wf;
  const zf = zDist / (zDist - z3);
  return [x3 * zf, y3 * zf];
}

function makeTesseract(opts) {
  return {
    scale: opts.scale || 1,
    orbitRadius: opts.orbitRadius || 0,
    orbitSpeed: opts.orbitSpeed || 0,
    orbitAngle: Math.random() * Math.PI * 2,
    phase: Math.random() * Math.PI * 2,
    forceFull: !!opts.forceFull,
    unlockedAt: opts.unlockedAt || 0,
    itemsAtUnlock: opts.itemsAtUnlock || 0,
    itemsTarget: opts.itemsTarget || 1,
    minBuildMs: opts.minBuildMs || 6000,
  };
}

function tesseractRevealFraction(inst, ts) {
  if (inst.forceFull) return 1;
  const timeFrac = Math.min(1, (ts - inst.unlockedAt) / inst.minBuildMs);
  const itemFrac = Math.min(1, Math.max(0, stats.items - inst.itemsAtUnlock) / inst.itemsTarget);
  return Math.min(timeFrac, itemFrac);
}

// Draws one hypercube, returns its vertices' final on-screen positions so a
// caller (the results view) can attach labeled nodes to them.
function drawTesseract(ctx, cx, cy, baseRadius, ts, inst) {
  const frac = tesseractRevealFraction(inst, ts);
  const revealedCount = Math.max(1, Math.floor(frac * TESS_BUILD_ORDER.length));
  const angleXW = ts * 0.00035 + inst.phase;
  const angleYZ = ts * 0.00023 + inst.phase * 1.3;
  const angleXY = ts * 0.00012;

  let ox = cx, oy = cy;
  if (inst.orbitRadius) {
    const orbitAngle = inst.orbitAngle + ts * inst.orbitSpeed * 0.0003;
    ox = cx + Math.cos(orbitAngle) * inst.orbitRadius * baseRadius;
    oy = cy + Math.sin(orbitAngle) * inst.orbitRadius * baseRadius;
  }
  const r = baseRadius * inst.scale * 0.4;

  const projected = TESS_VERTS.map((v) => {
    const rotated = rotate4D(v, angleXW, angleYZ, angleXY);
    const [x2, y2] = project4D(rotated, 3, 3.6);
    return [ox + x2 * r, oy + y2 * r];
  });

  for (let idx = 0; idx < revealedCount; idx++) {
    const step = TESS_BUILD_ORDER[idx];
    if (step.type !== 'edge') continue;
    const [x1, y1] = projected[step.a];
    const [x2, y2] = projected[step.b];
    ctx.strokeStyle = 'rgba(111, 159, 242, 0.5)';
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(x1, y1);
    ctx.lineTo(x2, y2);
    ctx.stroke();
  }
  for (let idx = 0; idx < revealedCount; idx++) {
    const step = TESS_BUILD_ORDER[idx];
    if (step.type !== 'vertex') continue;
    const [x, y] = projected[step.i];
    ctx.beginPath();
    ctx.fillStyle = '#eaf6ff';
    ctx.shadowColor = '#6f9ff2';
    ctx.shadowBlur = 7;
    ctx.arc(x, y, 2.2, 0, Math.PI * 2);
    ctx.fill();
    ctx.shadowBlur = 0;
  }

  return projected;
}

function showTooltip(evt, node) {
  const box = document.getElementById('tooltip');
  box.innerHTML = '';
  const nameEl = document.createElement('div');
  nameEl.className = 'tooltip-name';
  nameEl.textContent = node.name;
  const sizeEl = document.createElement('div');
  sizeEl.className = 'tooltip-size';
  sizeEl.textContent = formatBytes(node.size);
  box.appendChild(nameEl);
  box.appendChild(sizeEl);
  if (node.flag) {
    const badge = document.createElement('div');
    badge.className = 'badge badge-' + node.flag.level + ' tooltip-badge';
    badge.textContent = node.flag.level === 'safe' ? 'Safe to delete' : node.flag.level === 'review' ? 'Worth a look' : 'Keep';
    box.appendChild(badge);
    const reason = document.createElement('div');
    reason.className = 'tooltip-reason';
    reason.textContent = node.flag.reason;
    box.appendChild(reason);
  }
  box.hidden = false;
  let x, y;
  if (evt.type === 'focus') {
    const r = evt.target.getBoundingClientRect();
    x = r.left + r.width / 2;
    y = r.top - 8;
  } else {
    x = evt.clientX + 16;
    y = evt.clientY + 16;
  }
  box.style.left = x + 'px';
  box.style.top = y + 'px';
}

function hideTooltip() {
  document.getElementById('tooltip').hidden = true;
}

function sumByLevel(node, level) {
  let total = 0;
  if (node.flag && node.flag.level === level) return node.size;
  for (const child of node.children) total += sumByLevel(child, level);
  return total;
}

function renderSummary() {
  const totalScanned = forest.reduce((sum, r) => sum + r.size, 0);
  const safeTotal = forest.reduce((sum, r) => sum + sumByLevel(r, 'safe'), 0);
  const reviewTotal = forest.reduce((sum, r) => sum + sumByLevel(r, 'review'), 0);

  document.getElementById('statTotal').textContent = formatBytes(totalScanned);
  document.getElementById('statSafe').textContent = formatBytes(safeTotal);
  document.getElementById('statReview').textContent = formatBytes(reviewTotal);
  document.getElementById('statItems').textContent = stats.items.toLocaleString();

  const skippedNote = document.getElementById('skippedNote');
  if (stats.skipped > 0) {
    skippedNote.hidden = false;
    skippedNote.textContent = `${stats.skipped.toLocaleString()} item(s) couldn't be read (permission denied) and were skipped.`;
  } else {
    skippedNote.hidden = true;
  }
}

function updateProgressText() {
  document.getElementById('progressText').textContent =
    `Scanning… ${stats.items.toLocaleString()} items found`;
}

// --- Live scan visualization: the tesseract being built ---
// A single hypercube starts assembling the instant a scan begins. Its
// reveal speed is `Math.min(timeFraction, itemFraction)` (see
// `tesseractRevealFraction`) — deliberately the *slower* of "how much wall
// time has passed" and "how many real items have been found," which is
// what makes it both properly slow (a fast scan of a small folder still
// takes `minBuildMs` to visibly finish, so there's something to watch) and
// still tied to real data (a slow scan of a huge folder never finishes
// "early" just because a clock ran out). Bigger scans unlock additional,
// smaller satellite hypercubes orbiting the first — a nod to the
// escalating-scale structure of Idle Cosmos, where more real usage
// unlocks the next thing out. `onDiscover` only spawns a drifting spark,
// never a full render — that's what keeps a six-figure item count from
// ever blocking a frame.

const LIVE_SATELLITE_THRESHOLDS = [3000, 12000, 40000, 120000];
const LIVE_PARTICLE_CAP = 260;

let liveInstances = [];
let liveParticles = [];
let liveRafId = null;
let liveVizActive = false;

function unlockLiveSatellites() {
  LIVE_SATELLITE_THRESHOLDS.forEach((threshold, idx) => {
    if (stats.items >= threshold && liveInstances.length === idx + 1) {
      const next = LIVE_SATELLITE_THRESHOLDS[idx + 1] || threshold * 3;
      liveInstances.push(makeTesseract({
        scale: 0.55 - idx * 0.07,
        orbitRadius: 0.62 + idx * 0.17,
        orbitSpeed: 0.15 + idx * 0.05,
        unlockedAt: performance.now(),
        itemsAtUnlock: threshold,
        itemsTarget: next - threshold,
        minBuildMs: 5000,
      }));
    }
  });
}

function resizeCanvasTo(canvasId) {
  const canvas = document.getElementById(canvasId);
  const rect = canvas.getBoundingClientRect();
  if (rect.width === 0) return;
  const dpr = window.devicePixelRatio || 1;
  canvas.width = rect.width * dpr;
  canvas.height = rect.height * dpr;
}

function drawParticles(ctx, cx, cy, radius, ts, particles) {
  for (let i = particles.length - 1; i >= 0; i--) {
    const p = particles[i];
    const age = ts - p.born;
    if (age > 6000) { particles.splice(i, 1); continue; }
    const dist = p.dist * radius * (1 + age * 0.00004);
    const x = cx + Math.cos(p.angle) * dist;
    const y = cy + Math.sin(p.angle) * dist;
    const fade = age < 400 ? age / 400 : Math.max(0, 1 - (age - 4000) / 2000);
    ctx.beginPath();
    ctx.fillStyle = p.color;
    ctx.globalAlpha = 0.8 * fade;
    ctx.shadowColor = p.color;
    ctx.shadowBlur = 4;
    ctx.arc(x, y, p.size, 0, Math.PI * 2);
    ctx.fill();
    ctx.shadowBlur = 0;
    ctx.globalAlpha = 1;
  }
}

function liveFrame(ts) {
  unlockLiveSatellites();

  const canvas = document.getElementById('liveCanvas');
  const ctx = canvas.getContext('2d');
  const w = canvas.width, h = canvas.height;
  ctx.clearRect(0, 0, w, h);
  const cx = w / 2, cy = h / 2;
  const baseRadius = Math.min(w, h) * 0.46;

  drawParticles(ctx, cx, cy, baseRadius, ts, liveParticles);
  for (const inst of liveInstances) drawTesseract(ctx, cx, cy, baseRadius, ts, inst);

  if (liveVizActive) liveRafId = requestAnimationFrame(liveFrame);
}

function startLiveViz() {
  const now = performance.now();
  liveInstances = [makeTesseract({ scale: 1, unlockedAt: now, itemsAtUnlock: 0, itemsTarget: LIVE_SATELLITE_THRESHOLDS[0], minBuildMs: 7500 })];
  liveParticles = [];
  liveVizActive = true;
  onDiscover = (item) => {
    if (liveParticles.length >= LIVE_PARTICLE_CAP) liveParticles.shift();
    liveParticles.push({
      color: tessColorFor(item),
      born: performance.now(),
      angle: Math.random() * Math.PI * 2,
      dist: 0.25 + Math.random() * 0.95,
      size: item.flag ? 2.6 : 1.3,
    });
  };
  resizeCanvasTo('liveCanvas');
  liveRafId = requestAnimationFrame(liveFrame);
}

function stopLiveViz() {
  liveVizActive = false;
  onDiscover = () => {};
  if (liveRafId) cancelAnimationFrame(liveRafId);
  liveRafId = null;
  liveInstances = [];
  liveParticles = [];
}

// --- Results view: the finished tesseract ---
// Once a scan completes, the same engine renders a fully-assembled (or
// multi-hypercube, if the scan was big enough to unlock satellites)
// structure, now static geometry with real "notable item" nodes attached
// to its vertices — the biggest top-level things found, colored by
// verdict, sized by their share of what was scanned. There's no zoom/
// breadcrumb here (unlike the old sunburst) — 16 vertices per hypercube is
// a fixed number of slots, not an arbitrarily deep hierarchy, so instead
// clicking a node jumps to the List view, which has the real recursive
// breakdown.

let resultsInstances = [];
let resultsNodes = [];
let resultsFrozenTs = 0;
let inspectedItem = null;

function getNotableItems(limit) {
  const all = [];
  for (const root of forest) all.push(...root.children);
  all.sort((a, b) => b.size - a.size);
  if (all.length <= limit) return all;
  const shown = all.slice(0, limit - 1);
  const rest = all.slice(limit - 1);
  const otherSize = rest.reduce((sum, c) => sum + c.size, 0);
  shown.push({ name: `+${rest.length} more`, size: otherSize, flag: null, children: [] });
  return shown;
}

function sizeToNodeRadius(bytes) {
  return Math.min(13, Math.max(3, Math.log2((bytes || 1) + 1) * 0.7));
}

// "Intelligent" here means the graph reflects real containment, not
// decoration: each top-level item ("primary", pinned to a tesseract
// vertex) that has children gets up to 3 "child" nodes for its own
// biggest sub-items, branching outward from it. The spoke connecting them
// is drawn from the primary's actual resolved position, not a fixed
// tesseract edge — this is real hierarchy layered on top of the fixed
// geometric frame, which is why it has to happen in `renderResultsStatic`
// (positions only exist once the frame's vertices are projected) rather
// than at build time.
function buildResultsTesseract() {
  resultsInstances = [makeTesseract({ scale: 1, forceFull: true })];
  for (const threshold of LIVE_SATELLITE_THRESHOLDS) {
    if (stats.items < threshold) break;
    const idx = resultsInstances.length - 1;
    resultsInstances.push(makeTesseract({ scale: 0.55 - idx * 0.07, orbitRadius: 0.62 + idx * 0.17, orbitSpeed: 0.15 + idx * 0.05, forceFull: true }));
  }
  const primaries = getNotableItems(resultsInstances.length * 16);
  resultsNodes = [];
  primaries.forEach((item, idx) => {
    const primaryNode = { item, kind: 'primary', instanceIndex: Math.floor(idx / 16), vertexIndex: idx % 16, x: 0, y: 0, r: 0 };
    resultsNodes.push(primaryNode);
    if (!item.children || item.children.length === 0) return;
    const kids = item.children.filter((c) => c.size > 0).sort((a, b) => b.size - a.size).slice(0, 3);
    kids.forEach((kid, kidx) => {
      resultsNodes.push({ item: kid, kind: 'child', parent: primaryNode, siblingIndex: kidx, siblingCount: kids.length, x: 0, y: 0, r: 0 });
    });
  });
}

// Renders one still frame at a fixed timestamp — called once after a scan
// finishes, and again (with the *same* frozen timestamp) on tab-switch-in
// or window resize, so the frozen orientation never drifts. There is no
// requestAnimationFrame loop here on purpose: this view is meant to be
// held still long enough to actually click things, unlike the live scan
// show, which is meant to move.
function renderResultsStatic(ts) {
  const canvas = document.getElementById('resultsCanvas');
  const ctx = canvas.getContext('2d');
  const w = canvas.width, h = canvas.height;
  ctx.clearRect(0, 0, w, h);
  const cx = w / 2, cy = h / 2;
  const baseRadius = Math.min(w, h) * 0.46;

  const projectedByInstance = resultsInstances.map((inst) => drawTesseract(ctx, cx, cy, baseRadius, ts, inst));

  for (const rn of resultsNodes) {
    if (rn.kind !== 'primary') continue;
    const projected = projectedByInstance[rn.instanceIndex];
    if (!projected) continue;
    const [x, y] = projected[rn.vertexIndex];
    rn.x = x; rn.y = y;
    rn.r = sizeToNodeRadius(rn.item.size);
  }
  for (const rn of resultsNodes) {
    if (rn.kind !== 'child') continue;
    const p = rn.parent;
    const dist = Math.hypot(p.x - cx, p.y - cy) || 1;
    const dirX = (p.x - cx) / dist, dirY = (p.y - cy) / dist;
    const spokeLen = 24 + rn.siblingIndex * 20;
    const spread = (rn.siblingIndex - (rn.siblingCount - 1) / 2) * 0.4;
    const cosA = Math.cos(spread), sinA = Math.sin(spread);
    rn.x = p.x + (dirX * cosA - dirY * sinA) * spokeLen;
    rn.y = p.y + (dirX * sinA + dirY * cosA) * spokeLen;
    rn.r = sizeToNodeRadius(rn.item.size) * 0.75;
  }

  for (const rn of resultsNodes) {
    if (rn.kind !== 'child') continue;
    ctx.strokeStyle = tessColorFor(rn.item) + '66';
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(rn.parent.x, rn.parent.y);
    ctx.lineTo(rn.x, rn.y);
    ctx.stroke();
  }
  for (const rn of resultsNodes) {
    const dim = activeFilter !== 'all' && !(rn.item.flag && rn.item.flag.level === activeFilter);
    ctx.beginPath();
    ctx.fillStyle = tessColorFor(rn.item);
    ctx.globalAlpha = dim ? 0.18 : rn.kind === 'child' ? 0.85 : 0.95;
    ctx.shadowColor = ctx.fillStyle;
    ctx.shadowBlur = rn.item.flag ? 10 : 4;
    ctx.arc(rn.x, rn.y, rn.r, 0, Math.PI * 2);
    ctx.fill();
    ctx.shadowBlur = 0;
    ctx.globalAlpha = 1;
  }
}

function startResultsViz() {
  buildResultsTesseract();
  resultsFrozenTs = performance.now();
  resizeCanvasTo('resultsCanvas');
  renderResultsStatic(resultsFrozenTs);
}

function resultsHitTest(clientX, clientY) {
  const canvas = document.getElementById('resultsCanvas');
  const rect = canvas.getBoundingClientRect();
  const dpr = window.devicePixelRatio || 1;
  const mx = (clientX - rect.left) * dpr;
  const my = (clientY - rect.top) * dpr;
  let hit = null, hitDist = Infinity;
  for (const rn of resultsNodes) {
    const d = Math.hypot(mx - rn.x, my - rn.y);
    const hitR = Math.max(rn.r, 8) + 4;
    if (d <= hitR && d < hitDist) { hit = rn; hitDist = d; }
  }
  return hit;
}

function showInspector(item) {
  inspectedItem = item;
  document.getElementById('mapInspectorName').textContent = item.name;
  document.getElementById('mapInspectorSize').textContent = formatBytes(item.size);
  const badgeWrap = document.getElementById('mapInspectorBadge');
  badgeWrap.innerHTML = '';
  const reasonEl = document.getElementById('mapInspectorReason');
  if (item.flag) {
    const badge = document.createElement('span');
    badge.className = 'badge badge-' + item.flag.level;
    badge.textContent = item.flag.level === 'safe' ? 'Safe to delete' : item.flag.level === 'review' ? 'Worth a look' : 'Keep';
    badgeWrap.appendChild(badge);
    reasonEl.textContent = item.flag.reason;
    reasonEl.hidden = false;
  } else {
    reasonEl.textContent = '';
    reasonEl.hidden = true;
  }
  document.getElementById('mapInspector').hidden = false;
}

document.getElementById('liveCanvas').addEventListener('pointermove', hideTooltip);
document.getElementById('resultsCanvas').addEventListener('pointermove', (e) => {
  const hit = resultsHitTest(e.clientX, e.clientY);
  e.target.style.cursor = hit ? 'pointer' : 'default';
  if (hit) showTooltip(e, hit.item);
  else hideTooltip();
});
document.getElementById('resultsCanvas').addEventListener('pointerleave', hideTooltip);
document.getElementById('resultsCanvas').addEventListener('click', (e) => {
  const hit = resultsHitTest(e.clientX, e.clientY);
  if (hit) showInspector(hit.item);
});
document.getElementById('mapInspectorClose').addEventListener('click', () => {
  document.getElementById('mapInspector').hidden = true;
});
document.getElementById('mapInspectorGoto').addEventListener('click', () => {
  document.querySelector('.view-tab[data-view="list"]').click();
});
window.addEventListener('resize', () => {
  if (liveVizActive) resizeCanvasTo('liveCanvas');
  if (!document.getElementById('tesseractView').hidden) {
    resizeCanvasTo('resultsCanvas');
    renderResultsStatic(resultsFrozenTs);
  }
});

// --- Wiring ---

function showError(err) {
  const box = document.getElementById('errorNotice');
  if (location.protocol === 'file:') {
    box.textContent = "This can't run when the page is opened directly as a file (the address bar shows file://) — Chrome blocks folder access there for security. Serve this folder locally instead: open Terminal, cd into this folder, run \"python3 -m http.server\", then visit http://localhost:8000 in Chrome. (The version hosted on GitHub Pages, once pushed, won't have this problem.)";
  } else {
    box.textContent = 'Something went wrong: ' + (err && err.message ? err.message : String(err));
  }
  box.hidden = false;
}

async function runScan(startIn) {
  const supported = 'showDirectoryPicker' in window;
  if (!supported) {
    document.getElementById('unsupported').hidden = false;
    return;
  }
  document.getElementById('errorNotice').hidden = true;

  let handle;
  try {
    // `startIn` only points the OS dialog's starting folder — it grants no
    // access by itself. The user still has to pick and confirm a folder,
    // same as any other call.
    handle = await window.showDirectoryPicker(startIn ? { startIn } : undefined);
  } catch (err) {
    if (err && err.name === 'AbortError') return; // user cancelled the picker
    showError(err);
    return;
  }

  document.getElementById('progress').hidden = false;
  document.getElementById('scanBtn').disabled = true;
  scanTicker = setInterval(updateProgressText, 150);
  startLiveViz();

  try {
    const root = await scanEntry(handle, handle.name, 0, true, handle.name);
    forest.push(root);
    forest.sort((a, b) => b.size - a.size);

    document.getElementById('intro').hidden = true;
    document.getElementById('results').hidden = false;
    renderSummary();
    renderTree();
    startResultsViz();
  } catch (err) {
    showError(err);
  } finally {
    clearInterval(scanTicker);
    stopLiveViz();
    document.getElementById('progress').hidden = true;
    document.getElementById('scanBtn').disabled = false;
  }
}

document.getElementById('scanBtn').addEventListener('click', () => runScan());
document.getElementById('scanAppsBtn').addEventListener('click', () => runScan());
document.getElementById('scanLibraryBtn').addEventListener('click', () => runScan());
document.getElementById('scanAnotherBtn').addEventListener('click', () => runScan());
document.querySelectorAll('.btn-chip').forEach((btn) => {
  btn.addEventListener('click', () => runScan(btn.dataset.startin));
});

document.querySelectorAll('.filter-pill').forEach((pill) => {
  pill.addEventListener('click', () => {
    document.querySelectorAll('.filter-pill').forEach((p) => p.classList.remove('active'));
    pill.classList.add('active');
    activeFilter = pill.dataset.filter;
    renderTree();
    // The Map view is a still frame, not a loop — it needs an explicit
    // re-render (at the same frozen orientation) to pick up a filter change.
    if (resultsNodes.length) renderResultsStatic(resultsFrozenTs);
  });
});

document.querySelectorAll('.view-tab').forEach((tab) => {
  tab.addEventListener('click', () => {
    document.querySelectorAll('.view-tab').forEach((t) => {
      t.classList.remove('active');
      t.setAttribute('aria-selected', 'false');
    });
    tab.classList.add('active');
    tab.setAttribute('aria-selected', 'true');
    const view = tab.dataset.view;
    document.getElementById('tesseractView').hidden = view !== 'tesseract';
    document.getElementById('listView').hidden = view !== 'list';
    if (view === 'tesseract') {
      // Re-measure + redraw at the same frozen timestamp: a hidden canvas
      // reports zero size, so switching back in needs a fresh resize, but
      // the orientation itself must never drift between visits.
      resizeCanvasTo('resultsCanvas');
      renderResultsStatic(resultsFrozenTs);
    }
  });
});

if (!('showDirectoryPicker' in window)) {
  document.getElementById('unsupported').hidden = false;
  document.getElementById('scanBtn').disabled = true;
}
