// Pure data: no logic, no DOM access.
//
// architectureTags describes the GALLERY BUILDING's style (Renaissance,
// Brutalist, Deconstructivist, etc). This is a completely separate
// vocabulary from ART_MOVEMENTS in artworks-data.js, which describes the
// paintings/sculptures INSIDE the building. Brutalism, for example, is an
// architecture style and belongs only here — never as an artwork movement.
//
// coords ({lat, lon}) are city/campus-level approximations (not exact
// building entrances) — precise enough for the world-map view's pins,
// not for turn-by-turn navigation.

export const ARCHITECTURE_STYLES = [
  { slug: "renaissance", label: "Renaissance", gradient: ["#d9c9a3", "#8a6432"] },
  { slug: "baroque", label: "Baroque", gradient: ["#e8d5b7", "#a97a3f"] },
  { slug: "neoclassical", label: "Neoclassical", gradient: ["#e6ded0", "#a08c64"] },
  { slug: "beaux-arts", label: "Beaux-Arts", gradient: ["#ece2c8", "#af9558"] },
  { slug: "gothic-revival", label: "Gothic Revival", gradient: ["#c9cdd6", "#5b6478"] },
  { slug: "modernist", label: "Modernist", gradient: ["#dfe3e6", "#7c8894"] },
  { slug: "brutalist", label: "Brutalist", gradient: ["#c7c4bd", "#57534a"] },
  { slug: "deconstructivist", label: "Deconstructivist", gradient: ["#e0d8e8", "#6b4f8a"] },
  { slug: "high-tech", label: "High-Tech", gradient: ["#d6e6e8", "#3f7f8a"] },
  { slug: "industrial-conversion", label: "Industrial Conversion", gradient: ["#e0d6c8", "#8a6a48"] },
  { slug: "contemporary", label: "Contemporary", gradient: ["#dce4dc", "#5a7a68"] },
];

export const GALLERIES = [
  {
    id: "louvre",
    name: "The Louvre",
    city: "Paris",
    country: "France",
    continent: "Europe",
    coords: { lat: 48.8606, lon: 2.3376 },
    yearOpened: 1793,
    architect: "Pierre Lescot (original palace); I. M. Pei (glass pyramid, 1989)",
    architectureStyle: "Renaissance and Baroque royal palace with a modernist glass-pyramid entrance",
    architectureTags: ["renaissance", "baroque", "modernist"],
    description:
      "Once a medieval fortress and the residence of French kings, the Louvre was opened as a public museum in 1793 during the Revolution. Its vast wings of Renaissance and Baroque stonework now wrap around I. M. Pei's glass pyramid, added in 1989 as the museum's main entrance — a deliberate collision of centuries that has become one of the most photographed spots in Paris.",
    wikiTitle: "Louvre",
  },
  {
    id: "moma",
    name: "Museum of Modern Art (MoMA)",
    city: "New York City",
    country: "United States",
    continent: "North America",
    coords: { lat: 40.7614, lon: -73.9776 },
    yearOpened: 1929,
    architect: "Philip Goodwin & Edward Durell Stone (1939 building); Yoshio Taniguchi (2004 expansion)",
    architectureStyle: "International Style Modernism",
    architectureTags: ["modernist"],
    description:
      "Founded in 1929 in the wake of the Armory Show's introduction of European avant-garde art to America, MoMA moved into its International Style home on 53rd Street in 1939. Clean glass curtain walls and open, unornamented galleries were themselves a modernist statement — a building designed to disappear behind the art.",
    wikiTitle: "Museum of Modern Art",
  },
  {
    id: "uffizi",
    name: "Uffizi Gallery",
    city: "Florence",
    country: "Italy",
    continent: "Europe",
    coords: { lat: 43.7687, lon: 11.2551 },
    yearOpened: 1581,
    architect: "Giorgio Vasari",
    architectureStyle: "Renaissance",
    architectureTags: ["renaissance"],
    description:
      "Built in the 1560s by Giorgio Vasari as the administrative offices ('uffizi') of the Medici, the long U-shaped courtyard building was converted into a gallery for the family's art collection and opened to visitors by request as early as 1581 — making it one of the oldest museums in the world. Its arcaded facades still frame a straight sightline to the Arno river.",
    wikiTitle: "Uffizi",
  },
  {
    id: "hermitage",
    name: "State Hermitage Museum",
    city: "Saint Petersburg",
    country: "Russia",
    continent: "Europe",
    coords: { lat: 59.9398, lon: 30.3146 },
    yearOpened: 1764,
    architect: "Bartolomeo Rastrelli (Winter Palace, 1762)",
    architectureStyle: "Baroque and Rococo",
    architectureTags: ["baroque"],
    description:
      "Housed primarily in the Winter Palace, the turquoise-and-gold Baroque residence Bartolomeo Rastrelli built for the Russian tsars, the Hermitage began as Catherine the Great's private art collection in 1764. Six historic buildings now sprawl along the Neva embankment, their gilded facades among the most ornate surviving examples of Russian Baroque.",
    wikiTitle: "Hermitage Museum",
  },
  {
    id: "rijksmuseum",
    name: "Rijksmuseum",
    city: "Amsterdam",
    country: "Netherlands",
    continent: "Europe",
    coords: { lat: 52.3600, lon: 4.8852 },
    yearOpened: 1885,
    architect: "Pierre Cuypers",
    architectureStyle: "Gothic and Renaissance Revival",
    architectureTags: ["gothic-revival", "renaissance"],
    description:
      "Pierre Cuypers designed this cathedral-like brick landmark in a personal blend of Dutch Gothic and Renaissance Revival detailing, complete with turrets and stained glass — so ecclesiastical in feeling that King William III reportedly refused to set foot in it. A cycling tunnel still runs straight through the building's center, a quirk locals fought to preserve during a major 2000s renovation.",
    wikiTitle: "Rijksmuseum",
  },
  {
    id: "prado",
    name: "Museo del Prado",
    city: "Madrid",
    country: "Spain",
    continent: "Europe",
    coords: { lat: 40.4138, lon: -3.6921 },
    yearOpened: 1819,
    architect: "Juan de Villanueva",
    architectureStyle: "Neoclassical",
    architectureTags: ["neoclassical"],
    description:
      "Juan de Villanueva designed this long, colonnaded building in the 1780s to house a natural history cabinet for King Charles III; it opened instead as a royal art museum in 1819. Its restrained Neoclassical facade of granite and pink stone was conceived as a deliberate showcase of Spanish taste to rival the great collections of Paris and London.",
    wikiTitle: "Museo del Prado",
  },
  {
    id: "guggenheim-nyc",
    name: "Solomon R. Guggenheim Museum",
    city: "New York City",
    country: "United States",
    continent: "North America",
    coords: { lat: 40.7830, lon: -73.9590 },
    yearOpened: 1959,
    architect: "Frank Lloyd Wright",
    architectureStyle: "Organic Modernism",
    architectureTags: ["modernist"],
    description:
      "Frank Lloyd Wright's only museum design abandons conventional floors entirely: a continuous spiral ramp winds upward around a vast skylit atrium, so visitors can ride an elevator to the top and view art while walking gently downhill. Wright died six months before it opened in 1959, and its curving concrete drum still looks startlingly futuristic against Fifth Avenue's rectilinear skyline.",
    wikiTitle: "Solomon R. Guggenheim Museum",
  },
  {
    id: "hirshhorn",
    name: "Hirshhorn Museum and Sculpture Garden",
    city: "Washington, D.C.",
    country: "United States",
    continent: "North America",
    coords: { lat: 38.8882, lon: -77.0199 },
    yearOpened: 1974,
    architect: "Gordon Bunshaft (Skidmore, Owings & Merrill)",
    architectureStyle: "Brutalist",
    architectureTags: ["brutalist"],
    description:
      "A windowless concrete cylinder raised on four massive piers over the National Mall, Gordon Bunshaft's 1974 design was nicknamed the 'Brutalist doughnut' almost immediately. Its bush-hammered concrete drum and sunken sculpture garden make it one of the purest and most recognizable examples of Brutalist museum architecture anywhere in the world.",
    wikiTitle: "Hirshhorn Museum and Sculpture Garden",
  },
  {
    id: "pompidou",
    name: "Centre Pompidou",
    city: "Paris",
    country: "France",
    continent: "Europe",
    coords: { lat: 48.8607, lon: 2.3522 },
    yearOpened: 1977,
    architect: "Renzo Piano & Richard Rogers",
    architectureStyle: "High-Tech / Structural Expressionism",
    architectureTags: ["high-tech"],
    description:
      "Renzo Piano and Richard Rogers turned a building inside out: structural steel trusses, escalators, and color-coded service pipes (blue for air, green for water, yellow for electricity) all run across the exterior, leaving the interior as open, column-free loft space. Parisians were scandalized when it opened in 1977; it's now considered a defining work of High-Tech architecture.",
    wikiTitle: "Centre Pompidou",
  },
  {
    id: "guggenheim-bilbao",
    name: "Guggenheim Museum Bilbao",
    city: "Bilbao",
    country: "Spain",
    continent: "Europe",
    coords: { lat: 43.2687, lon: -2.9340 },
    yearOpened: 1997,
    architect: "Frank Gehry",
    architectureStyle: "Deconstructivism",
    architectureTags: ["deconstructivist"],
    description:
      "Frank Gehry's titanium-clad museum, its curved panels rippling like fish scales along the Nervión river, single-handedly revived a struggling industrial port city — a phenomenon now known as the 'Bilbao Effect.' The building has no single dominant facade; its warped, non-orthogonal forms were modeled using aerospace software never before applied to architecture.",
    wikiTitle: "Guggenheim Museum Bilbao",
  },
  {
    id: "nmwa-tokyo",
    name: "National Museum of Western Art",
    city: "Tokyo",
    country: "Japan",
    continent: "Asia",
    coords: { lat: 35.7156, lon: 139.7745 },
    yearOpened: 1959,
    architect: "Le Corbusier",
    architectureStyle: "Modernist",
    architectureTags: ["modernist"],
    description:
      "Le Corbusier's only building in East Asia was designed around his 'Museum of Unlimited Growth' concept: a square spiral plan meant to expand outward indefinitely as the collection grew. Raised on slender pilotis with a naturally lit central hall, it was jointly inscribed as a UNESCO World Heritage Site in 2016 alongside sixteen other Le Corbusier works across seven countries.",
    wikiTitle: "National Museum of Western Art",
  },
  {
    id: "masp",
    name: "Museu de Arte de São Paulo (MASP)",
    city: "São Paulo",
    country: "Brazil",
    continent: "South America",
    coords: { lat: -23.5614, lon: -46.6558 },
    yearOpened: 1968,
    architect: "Lina Bo Bardi",
    architectureStyle: "Brutalist (Paulista School)",
    architectureTags: ["brutalist"],
    description:
      "Lina Bo Bardi suspended a two-story red concrete-and-glass volume between two enormous concrete beams, lifting the entire museum eight meters off the ground and leaving a dramatic open civic plaza underneath. It's the signature work of São Paulo's 'Paulista' strand of Brutalism, and its famous glass-panel-on-concrete-cube easel displays leave paintings floating with no wall behind them.",
    wikiTitle: "Museu de Arte de São Paulo",
  },
  {
    id: "zeitz-mocaa",
    name: "Zeitz Museum of Contemporary Art Africa (Zeitz MOCAA)",
    city: "Cape Town",
    country: "South Africa",
    continent: "Africa",
    coords: { lat: -33.9075, lon: 18.4201 },
    yearOpened: 2017,
    architect: "Thomas Heatherwick (Heatherwick Studio)",
    architectureStyle: "Industrial Conversion",
    architectureTags: ["industrial-conversion"],
    description:
      "Thomas Heatherwick carved this museum out of a 1920s grain silo complex on Cape Town's waterfront, cutting a soaring, tube-shaped atrium through the raw concrete by taking a 3D scan of a single corn kernel and enlarging it to full building scale. The silo's original bins remain visible as cylindrical gallery walls, now housing the continent's largest collection of contemporary African and diaspora art.",
    wikiTitle: "Zeitz Museum of Contemporary Art Africa",
  },
  {
    id: "met",
    name: "The Metropolitan Museum of Art",
    city: "New York City",
    country: "United States",
    continent: "North America",
    coords: { lat: 40.7794, lon: -73.9632 },
    yearOpened: 1870,
    architect: "Calvert Vaux & Jacob Wrey Mould (original); Richard Morris Hunt (Fifth Avenue facade, 1902)",
    architectureStyle: "Beaux-Arts",
    architectureTags: ["beaux-arts"],
    description:
      "Founded in 1870 by a group of businessmen, artists, and financiers who wanted America to have a great encyclopedic museum of its own, the Met moved to its current Central Park site in 1880 and grew, wing by wing, into a limestone Beaux-Arts palace over two million square feet — now one of the largest art museums on Earth.",
    wikiTitle: "Metropolitan Museum of Art",
  },
  {
    id: "british-museum",
    name: "The British Museum",
    city: "London",
    country: "United Kingdom",
    continent: "Europe",
    coords: { lat: 51.5194, lon: -0.1270 },
    yearOpened: 1759,
    architect: "Robert Smirke (main building, 1852); Norman Foster (Great Court roof, 2000)",
    architectureStyle: "Neoclassical",
    architectureTags: ["neoclassical", "contemporary"],
    description:
      "Founded in 1753 around the personal collection of physician Sir Hans Sloane, the British Museum was the first national public museum in the world. Robert Smirke's colonnaded Greek Revival facade dates to the 1820s-50s; the glass-and-steel canopy roofing its central courtyard, designed by Norman Foster, was added in 2000 and is the largest covered public square in Europe.",
    wikiTitle: "British Museum",
  },
  {
    id: "national-gallery-london",
    name: "The National Gallery",
    city: "London",
    country: "United Kingdom",
    continent: "Europe",
    coords: { lat: 51.5089, lon: -0.1283 },
    yearOpened: 1824,
    architect: "William Wilkins (1838 building); Robert Venturi (Sainsbury Wing, 1991)",
    architectureStyle: "Neoclassical",
    architectureTags: ["neoclassical"],
    description:
      "Founded in 1824 when Parliament bought 38 paintings from a private banker's collection, the National Gallery has occupied its columned Trafalgar Square building since 1838. Unlike most national collections, it wasn't built from royal holdings — it was assembled from scratch specifically for public benefit, and remains free to enter.",
    wikiTitle: "National Gallery",
  },
  {
    id: "tate-modern",
    name: "Tate Modern",
    city: "London",
    country: "United Kingdom",
    continent: "Europe",
    coords: { lat: 51.5076, lon: -0.0994 },
    yearOpened: 2000,
    architect: "Giles Gilbert Scott (original power station, 1963); Herzog & de Meuron (museum conversion, 2000)",
    architectureStyle: "Industrial Conversion",
    architectureTags: ["industrial-conversion"],
    description:
      "Herzog & de Meuron converted Giles Gilbert Scott's disused Bankside Power Station — a single vast brick chimney beside the Thames — into Britain's national gallery of modern art, keeping the building's cavernous turbine hall intact as a dramatic entrance space for oversized installations.",
    wikiTitle: "Tate Modern",
  },
  {
    id: "musee-dorsay",
    name: "Musée d'Orsay",
    city: "Paris",
    country: "France",
    continent: "Europe",
    coords: { lat: 48.8600, lon: 2.3266 },
    yearOpened: 1986,
    architect: "Victor Laloux (original railway station, 1900); Gae Aulenti (museum conversion, 1986)",
    architectureStyle: "Beaux-Arts railway station conversion",
    architectureTags: ["beaux-arts", "industrial-conversion"],
    description:
      "Built as the Gare d'Orsay, a Beaux-Arts railway terminus for the 1900 World's Fair, the building fell out of use as trains grew too long for its platforms. Italian architect Gae Aulenti converted it into a museum in 1986, turning its glass-vaulted train shed into the light-filled central nave that now houses the world's largest Impressionist and Post-Impressionist collection.",
    wikiTitle: "Musée d'Orsay",
  },
  {
    id: "vatican-museums",
    name: "Vatican Museums",
    city: "Vatican City",
    country: "Vatican City",
    continent: "Europe",
    coords: { lat: 41.9065, lon: 12.4536 },
    yearOpened: 1506,
    architect: "Multiple Renaissance and Baroque architects across five centuries",
    architectureStyle: "Renaissance and Baroque",
    architectureTags: ["renaissance", "baroque"],
    description:
      "Founded in 1506 by Pope Julius II around a single ancient sculpture, the Vatican Museums have grown into a chain of palaces, galleries, and courtyards accumulated by successive popes — culminating in the Sistine Chapel, whose ceiling and altar wall Michelangelo painted between 1508 and 1541.",
    wikiTitle: "Vatican Museums",
  },
  {
    id: "art-institute-chicago",
    name: "Art Institute of Chicago",
    city: "Chicago",
    country: "United States",
    continent: "North America",
    coords: { lat: 41.8796, lon: -87.6237 },
    yearOpened: 1893,
    architect: "Shepley, Rutan and Coolidge; Renzo Piano (Modern Wing, 2009)",
    architectureStyle: "Beaux-Arts",
    architectureTags: ["beaux-arts", "contemporary"],
    description:
      "Built for the 1893 World's Columbian Exposition and guarded by its famous pair of bronze lions ever since, the Art Institute's Beaux-Arts limestone building on Michigan Avenue gained a glass-and-steel Modern Wing by Renzo Piano in 2009, connected to Millennium Park by a slender pedestrian bridge.",
    wikiTitle: "Art Institute of Chicago",
  },
  {
    id: "reina-sofia",
    name: "Museo Reina Sofía",
    city: "Madrid",
    country: "Spain",
    continent: "Europe",
    coords: { lat: 40.4084, lon: -3.6942 },
    yearOpened: 1992,
    architect: "Francesco Sabatini (original hospital, 18th c.); Jean Nouvel (extension, 2005)",
    architectureStyle: "Neoclassical hospital with a contemporary extension",
    architectureTags: ["neoclassical", "contemporary"],
    description:
      "Housed in a former 18th-century general hospital, the Reina Sofía opened as Spain's national museum of modern art in 1992, its severe neoclassical courtyards marked by two glass exterior elevators added in the 1980s. Jean Nouvel's angular red-steel extension, added in 2005, holds temporary exhibitions and a public library.",
    wikiTitle: "Museo Reina Sofía",
  },
  {
    id: "national-gallery-of-art-dc",
    name: "National Gallery of Art",
    city: "Washington, D.C.",
    country: "United States",
    continent: "North America",
    coords: { lat: 38.8913, lon: -77.0199 },
    yearOpened: 1941,
    architect: "John Russell Pope (West Building, 1941); I. M. Pei (East Building, 1978)",
    architectureStyle: "Neoclassical, with a modernist annex",
    architectureTags: ["neoclassical", "modernist"],
    description:
      "Financier Andrew Mellon donated both his art collection and the funds for the building, on the condition it never bear his name — it opened in 1941 as a gift to the nation. John Russell Pope's domed marble West Building sits across a plaza from I. M. Pei's angular, trapezoid-plan East Building, built in 1978 to fit an awkward wedge-shaped site.",
    wikiTitle: "National Gallery of Art",
  },
  {
    id: "philadelphia-museum-of-art",
    name: "Philadelphia Museum of Art",
    city: "Philadelphia",
    country: "United States",
    continent: "North America",
    coords: { lat: 39.9656, lon: -75.1810 },
    yearOpened: 1876,
    architect: "Horace Trumbauer, Julian Abele & Charles Borie",
    architectureStyle: "Neoclassical (Greek Revival)",
    architectureTags: ["neoclassical"],
    description:
      "Perched atop a hill at the end of the Benjamin Franklin Parkway, this Greek Revival temple of orange-tinged Minnesota dolomite is best known today for its 72-step entrance staircase, immortalized by the 1976 film Rocky — a piece of pop-culture fame the museum has since leaned into with a bronze statue of the fictional boxer at its base.",
    wikiTitle: "Philadelphia Museum of Art",
  },
  {
    id: "kunsthistorisches-museum",
    name: "Kunsthistorisches Museum",
    city: "Vienna",
    country: "Austria",
    continent: "Europe",
    coords: { lat: 48.2033, lon: 16.3616 },
    yearOpened: 1891,
    architect: "Gottfried Semper & Karl von Hasenauer",
    architectureStyle: "Renaissance Revival (Historicism)",
    architectureTags: ["renaissance"],
    description:
      "Built to finally give the Habsburg imperial art collection — accumulated over centuries by one of Europe's most avid dynasties of collectors — a permanent public home, this domed Ringstrasse palace opened in 1891 facing an identical twin building (the Natural History Museum) across a formal garden.",
    wikiTitle: "Kunsthistorisches Museum",
  },
  {
    id: "neue-nationalgalerie",
    name: "Neue Nationalgalerie",
    city: "Berlin",
    country: "Germany",
    continent: "Europe",
    coords: { lat: 52.5063, lon: 13.3676 },
    yearOpened: 1968,
    architect: "Ludwig Mies van der Rohe",
    architectureStyle: "Modernist",
    architectureTags: ["modernist"],
    description:
      "Mies van der Rohe's last building, completed the year before his death, is a glass box seemingly floating beneath a flat black-steel roof held up by just eight slender columns — an almost column-free temple to modernism that the architect considered the purest expression of his 'less is more' philosophy.",
    wikiTitle: "Neue Nationalgalerie",
  },
  {
    id: "galleria-borghese",
    name: "Galleria Borghese",
    city: "Rome",
    country: "Italy",
    continent: "Europe",
    coords: { lat: 41.9142, lon: 12.4922 },
    yearOpened: 1903,
    architect: "Flaminio Ponzio",
    architectureStyle: "Baroque",
    architectureTags: ["baroque"],
    description:
      "Built in the early 1600s as a lavish garden villa for the art-obsessed Cardinal Scipione Borghese, this compact Baroque pleasure palace was designed from the start to display his sculpture and painting collection, including several works he all but coerced Bernini and Caravaggio into giving him.",
    wikiTitle: "Galleria Borghese",
  },
  {
    id: "peggy-guggenheim-collection",
    name: "Peggy Guggenheim Collection",
    city: "Venice",
    country: "Italy",
    continent: "Europe",
    coords: { lat: 45.4308, lon: 12.3320 },
    yearOpened: 1951,
    architect: "Lorenzo Boschetti (18th-century palazzo)",
    architectureStyle: "Venetian palazzo (unfinished)",
    architectureTags: ["baroque"],
    description:
      "American heiress and collector Peggy Guggenheim bought this single-story, never-finished 18th-century palazzo on the Grand Canal in 1949 and lived among her own collection of Cubist, Surrealist, and Abstract Expressionist art until her death, after which it became a public museum exactly as she'd arranged it.",
    wikiTitle: "Peggy Guggenheim Collection",
  },
  {
    id: "van-gogh-museum",
    name: "Van Gogh Museum",
    city: "Amsterdam",
    country: "Netherlands",
    continent: "Europe",
    coords: { lat: 52.3584, lon: 4.8811 },
    yearOpened: 1973,
    architect: "Gerrit Rietveld (main building); Kisho Kurokawa (exhibition wing, 1999)",
    architectureStyle: "Modernist (De Stijl-adjacent)",
    architectureTags: ["modernist"],
    description:
      "Built specifically to house the collection assembled by Vincent van Gogh's brother Theo and passed down through his family, the museum's clean-lined main building was designed by Gerrit Rietveld, a founding figure of the De Stijl movement, and holds the largest collection of van Gogh's paintings and letters anywhere.",
    wikiTitle: "Van Gogh Museum",
  },
  {
    id: "belvedere",
    name: "Belvedere",
    city: "Vienna",
    country: "Austria",
    continent: "Europe",
    coords: { lat: 48.1912, lon: 16.3809 },
    yearOpened: 1781,
    architect: "Johann Lucas von Hildebrandt",
    architectureStyle: "Baroque",
    architectureTags: ["baroque"],
    description:
      "Built as a summer palace for Prince Eugene of Savoy, a celebrated military commander, the Belvedere's two ornate Baroque palaces sit at either end of a formal sloped garden. It opened to the public in 1781 as one of the first purpose-built public art galleries in Europe and now holds the world's largest Gustav Klimt collection.",
    wikiTitle: "Belvedere (palace)",
  },
  {
    id: "pushkin-museum",
    name: "Pushkin State Museum of Fine Arts",
    city: "Moscow",
    country: "Russia",
    continent: "Europe",
    coords: { lat: 55.7476, lon: 37.6053 },
    yearOpened: 1912,
    architect: "Roman Klein",
    architectureStyle: "Neoclassical",
    architectureTags: ["neoclassical"],
    description:
      "Founded as a teaching museum for Moscow University students, its Ionic-columned facade modeled on the Erechtheion in Athens, the Pushkin Museum grew after the Soviet era into one of Russia's two great encyclopedic collections, absorbing significant French Impressionist and modern holdings nationalized after the 1917 revolution.",
    wikiTitle: "Pushkin Museum",
  },
  {
    id: "tretyakov-gallery",
    name: "State Tretyakov Gallery",
    city: "Moscow",
    country: "Russia",
    continent: "Europe",
    coords: { lat: 55.7415, lon: 37.6208 },
    yearOpened: 1856,
    architect: "Viktor Vasnetsov (fairy-tale facade, 1902-04)",
    architectureStyle: "Russian Revival",
    architectureTags: ["gothic-revival"],
    description:
      "Merchant and collector Pavel Tretyakov began buying Russian art in 1856 with the explicit goal of founding a national gallery, and donated his entire collection to the city of Moscow in 1892. Its storybook red-and-white facade, added by painter Viktor Vasnetsov, deliberately evokes traditional Russian folk-tale architecture.",
    wikiTitle: "Tretyakov Gallery",
  },
  {
    id: "louisiana-museum",
    name: "Louisiana Museum of Modern Art",
    city: "Humlebæk",
    country: "Denmark",
    continent: "Europe",
    coords: { lat: 55.9694, lon: 12.5427 },
    yearOpened: 1958,
    architect: "Jørgen Bo & Vilhelm Wohlert",
    architectureStyle: "Scandinavian Modernist",
    architectureTags: ["modernist"],
    description:
      "Built around a 19th-century villa on a cliff-top estate overlooking the Øresund strait, Louisiana threads a series of low, glass-walled pavilions through the surrounding beech woods and sculpture garden, so that walking between galleries means constantly stepping back outside — a landscape-first approach that has influenced museum design worldwide.",
    wikiTitle: "Louisiana Museum of Modern Art",
  },
  {
    id: "isabella-stewart-gardner",
    name: "Isabella Stewart Gardner Museum",
    city: "Boston",
    country: "United States",
    continent: "North America",
    coords: { lat: 42.3382, lon: -71.0993 },
    yearOpened: 1903,
    architect: "Willard T. Sears, with Isabella Stewart Gardner",
    architectureStyle: "Venetian palazzo revival",
    architectureTags: ["renaissance"],
    description:
      "Boston socialite and collector Isabella Stewart Gardner built this faux-15th-century Venetian palazzo — complete with a glass-roofed central courtyard she filled with fresh flowers year-round — specifically to house her collection, then willed it to the public with the stipulation that nothing ever be rearranged. A 1990 heist, still unsolved, left several frames hanging empty exactly where the stolen paintings once hung.",
    wikiTitle: "Isabella Stewart Gardner Museum",
  },
  {
    id: "getty-center",
    name: "Getty Center",
    city: "Los Angeles",
    country: "United States",
    continent: "North America",
    coords: { lat: 34.0780, lon: -118.4740 },
    yearOpened: 1997,
    architect: "Richard Meier",
    architectureStyle: "Modernist",
    architectureTags: ["modernist"],
    description:
      "Richard Meier's hilltop campus above Los Angeles is clad almost entirely in rough-cut travertine shipped from the same Italian quarry that supplied the Colosseum, its gleaming white geometric pavilions connected by gardens and terraces with sweeping views from downtown L.A. to the Pacific.",
    wikiTitle: "Getty Center",
  },
  {
    id: "lacma",
    name: "Los Angeles County Museum of Art (LACMA)",
    city: "Los Angeles",
    country: "United States",
    continent: "North America",
    coords: { lat: 34.0637, lon: -118.3592 },
    yearOpened: 1965,
    architect: "William Pereira (1965 campus); Peter Zumthor (David Geffen Galleries, 2024)",
    architectureStyle: "Modernist, with a contemporary rebuild",
    architectureTags: ["modernist", "contemporary"],
    description:
      "LACMA sits directly beside the La Brea Tar Pits, and its original 1960s campus was gradually replaced by a single sinuous concrete-and-glass gallery building designed by Pritzker Prize-winning architect Peter Zumthor, an amoeba-like form raised on stilts that visitors enter from underneath.",
    wikiTitle: "Los Angeles County Museum of Art",
  },
  {
    id: "art-gallery-of-ontario",
    name: "Art Gallery of Ontario",
    city: "Toronto",
    country: "Canada",
    continent: "North America",
    coords: { lat: 43.6536, lon: -79.3925 },
    yearOpened: 1900,
    architect: "Frank Gehry (2008 renovation)",
    architectureStyle: "Deconstructivist renovation",
    architectureTags: ["deconstructivist"],
    description:
      "Frank Gehry, who grew up a few blocks away, returned to redesign his hometown gallery in 2008, wrapping the existing building in a swooping glass-and-wood facade and topping it with a twisting blue titanium sculpture gallery that reads as a piece of sculpture itself from the street.",
    wikiTitle: "Art Gallery of Ontario",
  },
  {
    id: "museo-soumaya",
    name: "Museo Soumaya",
    city: "Mexico City",
    country: "Mexico",
    continent: "North America",
    coords: { lat: 19.4402, lon: -99.2043 },
    yearOpened: 2011,
    architect: "Fernando Romero",
    architectureStyle: "Contemporary",
    architectureTags: ["contemporary"],
    description:
      "Built by billionaire Carlos Slim in honor of his late wife, this windowless, cloud-shaped tower is wrapped in 16,000 hexagonal aluminum tiles that shimmer like scales, engineered with input from Frank Gehry's studio — a deliberately futuristic landmark in the middle of the Plaza Carso development Slim built around it.",
    wikiTitle: "Museo Soumaya",
  },
  {
    id: "malba",
    name: "Museo de Arte Latinoamericano de Buenos Aires (MALBA)",
    city: "Buenos Aires",
    country: "Argentina",
    continent: "South America",
    coords: { lat: -34.5765, lon: -58.4028 },
    yearOpened: 2001,
    architect: "Gastón Atelman, Martín Fourcade & Alfredo Tapia",
    architectureStyle: "Contemporary",
    architectureTags: ["contemporary"],
    description:
      "Founded in 2001 to house businessman Eduardo Costantini's collection of 20th-century Latin American art, MALBA's clean-lined concrete-and-glass building was selected through an international competition specifically to avoid evoking any single national style — a deliberately pan-Latin-American design for a pan-Latin-American collection.",
    wikiTitle: "Museo de Arte Latinoamericano de Buenos Aires",
  },
  {
    id: "museo-de-arte-de-lima",
    name: "Museo de Arte de Lima (MALI)",
    city: "Lima",
    country: "Peru",
    continent: "South America",
    coords: { lat: -12.0619, lon: -77.0365 },
    yearOpened: 1961,
    architect: "Antonio Leonardi (Palacio de la Exposición, 1872)",
    architectureStyle: "Renaissance Revival (French Eclecticism)",
    architectureTags: ["renaissance"],
    description:
      "Housed in the ornate cast-iron-and-brick Palacio de la Exposición, built in 1872 for Lima's first World's Fair-style national exhibition, MALI opened in 1961 as the only museum offering a comprehensive survey of 3,000 years of Peruvian art, from pre-Columbian ceramics through contemporary work.",
    wikiTitle: "Lima Art Museum",
  },
  {
    id: "israel-museum",
    name: "The Israel Museum",
    city: "Jerusalem",
    country: "Israel",
    continent: "Asia",
    coords: { lat: 31.7719, lon: 35.2044 },
    yearOpened: 1965,
    architect: "Alfred Mansfeld & Dora Gad",
    architectureStyle: "Modernist",
    architectureTags: ["modernist"],
    description:
      "Designed as a hillside village of low white pavilions meant to blend into the Jerusalem landscape, the Israel Museum is best known for the Shrine of the Book, a white dome shaped like the lid of the ceramic jars in which the Dead Sea Scrolls were found, built directly across from a black basalt wall for contrast.",
    wikiTitle: "Israel Museum",
  },
  {
    id: "louvre-abu-dhabi",
    name: "Louvre Abu Dhabi",
    city: "Abu Dhabi",
    country: "United Arab Emirates",
    continent: "Asia",
    coords: { lat: 24.5335, lon: 54.3984 },
    yearOpened: 2017,
    architect: "Jean Nouvel",
    architectureStyle: "Contemporary",
    architectureTags: ["contemporary"],
    description:
      "Jean Nouvel's museum sits beneath a vast 180-meter perforated dome woven from eight layers of interlacing geometric steel patterns, inspired by the overlapping palm-frond roofs of traditional Arab architecture — sunlight filtering through it creates a shifting 'rain of light' across the plaza and galleries below.",
    wikiTitle: "Louvre Abu Dhabi",
  },
  {
    id: "national-museum-of-china",
    name: "National Museum of China",
    city: "Beijing",
    country: "China",
    continent: "Asia",
    coords: { lat: 39.9037, lon: 116.3975 },
    yearOpened: 1959,
    architect: "Zhang Kaiji (1959 building); Gerkan, Marg and Partners (2010 renovation)",
    architectureStyle: "Socialist Classicism, with a contemporary interior rebuild",
    architectureTags: ["neoclassical", "contemporary"],
    description:
      "Built in 1959 as one of the 'Ten Great Buildings' commissioned for the tenth anniversary of the People's Republic, facing the Great Hall of the People across Tiananmen Square, the museum was gutted and rebuilt behind its original facade in a 2010 renovation that made it, by floor area, one of the largest museums in the world.",
    wikiTitle: "National Museum of China",
  },
  {
    id: "m-plus",
    name: "M+",
    city: "Hong Kong",
    country: "China",
    continent: "Asia",
    coords: { lat: 22.3028, lon: 114.1596 },
    yearOpened: 2021,
    architect: "Herzog & de Meuron, with TFP Farrells and Arup",
    architectureStyle: "Contemporary",
    architectureTags: ["contemporary"],
    description:
      "Asia's first major museum dedicated to 20th- and 21st-century visual culture, M+ is built as a wide horizontal podium topped with a slim vertical tower, its BMW-sponsored facade of ceramic tiles doubling as a giant illuminated public art screen visible across Victoria Harbour at night.",
    wikiTitle: "M+",
  },
  {
    id: "national-museum-of-korea",
    name: "National Museum of Korea",
    city: "Seoul",
    country: "South Korea",
    continent: "Asia",
    coords: { lat: 37.5240, lon: 126.9803 },
    yearOpened: 1945,
    architect: "Jung Ki-chul & Park Seung-hong (2005 building)",
    architectureStyle: "Contemporary",
    architectureTags: ["contemporary"],
    description:
      "Founded in 1945 immediately after Korea's liberation, the museum moved into a purpose-built home in Yongsan Family Park in 2005 — a long, fortress-like building deliberately oriented to frame a view of Namsan mountain through a central gap, and now the sixth-largest museum in the world by floor area.",
    wikiTitle: "National Museum of Korea",
  },
  {
    id: "national-museum-new-delhi",
    name: "National Museum, New Delhi",
    city: "New Delhi",
    country: "India",
    continent: "Asia",
    coords: { lat: 28.6116, lon: 77.2196 },
    yearOpened: 1949,
    architect: "Ganesh Bhikaji Deolalikar",
    architectureStyle: "Modernist",
    architectureTags: ["modernist"],
    description:
      "Conceived after a landmark 1947-48 exhibition of Indian art in London, and inaugurated by Jawaharlal Nehru, India's National Museum moved into its current modernist building in 1960 — galleries arranged around a central courtyard, holding a collection spanning more than 5,000 years of the subcontinent's art and history.",
    wikiTitle: "National Museum, New Delhi",
  },
  {
    id: "national-gallery-singapore",
    name: "National Gallery Singapore",
    city: "Singapore",
    country: "Singapore",
    continent: "Asia",
    coords: { lat: 1.2903, lon: 103.8517 },
    yearOpened: 2015,
    architect: "studioMilou & CPG Consultants",
    architectureStyle: "Neoclassical colonial buildings with a contemporary canopy",
    architectureTags: ["neoclassical", "contemporary"],
    description:
      "Built by joining Singapore's former Supreme Court and City Hall — two Neoclassical colonial-era buildings — beneath a rippling bronze-and-glass canopy, the gallery opened in 2015 as the world's largest public collection of Singaporean and Southeast Asian modern art.",
    wikiTitle: "National Gallery Singapore",
  },
  {
    id: "national-gallery-of-australia",
    name: "National Gallery of Australia",
    city: "Canberra",
    country: "Australia",
    continent: "Oceania",
    coords: { lat: -35.3006, lon: 149.1350 },
    yearOpened: 1982,
    architect: "Colin Madigan",
    architectureStyle: "Brutalist",
    architectureTags: ["brutalist"],
    description:
      "Colin Madigan's angular, geometric Brutalist bunker on the shore of Lake Burley Griffin was built from bush-hammered concrete cast to resemble the surrounding eucalyptus forest's texture, and holds the world's largest single collection of Aboriginal and Torres Strait Islander art alongside its international galleries.",
    wikiTitle: "National Gallery of Australia",
  },
  {
    id: "art-gallery-of-new-south-wales",
    name: "Art Gallery of New South Wales",
    city: "Sydney",
    country: "Australia",
    continent: "Oceania",
    coords: { lat: -33.8688, lon: 151.2172 },
    yearOpened: 1874,
    architect: "Walter Liberty Vernon (1909 building); SANAA (Naala Badu expansion, 2022)",
    architectureStyle: "Neoclassical, with a contemporary pavilion",
    architectureTags: ["neoclassical", "contemporary"],
    description:
      "A colonnaded Victorian sandstone building overlooking Sydney Harbour gained a striking companion in 2022: Naala Badu, a cascade of low, light-filled pavilions by Japanese firm SANAA that steps down the hillside toward the water, roughly doubling the gallery's exhibition space.",
    wikiTitle: "Art Gallery of New South Wales",
  },
  {
    id: "egyptian-museum-cairo",
    name: "Egyptian Museum",
    city: "Cairo",
    country: "Egypt",
    continent: "Africa",
    coords: { lat: 30.0478, lon: 31.2336 },
    yearOpened: 1902,
    architect: "Marcel Dourgnon",
    architectureStyle: "Neoclassical",
    architectureTags: ["neoclassical"],
    description:
      "Overlooking Tahrir Square since 1902, this pink Neoclassical building was purpose-built to finally give Egypt's antiquities a secure, dedicated home after decades of foreign collectors carting artifacts abroad — for over a century it held the world's largest collection of Pharaonic antiquities, including Tutankhamun's treasures, before many moved to the newer Grand Egyptian Museum.",
    wikiTitle: "Egyptian Museum",
  },
  {
    id: "grand-egyptian-museum",
    name: "Grand Egyptian Museum",
    city: "Giza",
    country: "Egypt",
    continent: "Africa",
    coords: { lat: 29.9943, lon: 31.1214 },
    yearOpened: 2025,
    architect: "Heneghan Peng Architects",
    architectureStyle: "Contemporary",
    architectureTags: ["contemporary"],
    description:
      "Two kilometers from the Pyramids of Giza, this wedge-shaped concrete museum — its desert-facing wall wrapped in triangular panels of translucent alabaster, limestone, and glass — took over two decades and a billion dollars to complete, opening in full in late 2025 as the largest museum in the world devoted to a single civilization.",
    wikiTitle: "Grand Egyptian Museum",
  },
];
